import type { Chapter, QuizQuestion } from '../types'

const check = (id: string, unitId: string, prompt: string, options: string[], answer: number, explanation: string): QuizQuestion => ({ id, unitId, prompt, options, answer, explanation })

export const chapter3: Chapter = {
  id: 'chapter-3', number: 3, title: 'Bug（错误）、质量与 Self-healing（自我修复）',
  source: { start: 1151.08, end: 1866.98 },
  objectives: [
    '区分发布前预防、发布后识别、自动修复和架构改进四层质量工作。',
    '能依据文件敏感度、用户影响和错误类型选择自动或人工处理。',
    '理解 Agent Economy（智能体经济）与 SaaS（软件即服务）接口变化为何也属于系统重构。',
  ],
  interaction: { id: 'bug-triage-lab', kind: 'triage', title: 'Bug Triage（错误分诊）实验室', description: '把真实问题送入低、中、高风险通道，比较速度、成本和安全后果。' },
  recap: '质量不是追求永远没有错误，而是更早发现、更快分流，并把重复错误转化为系统改进。',
  next: '下一章回到组织转型过程，学习规划能力、可复用 Skill（技能规则）和生产率数字该怎样判断。',
  units: [
    {
      id: 'c3-bugs-inevitable', source: { start: 1151.08, end: 1173.6, speakers: [1] },
      title: '人工智能写代码并不会让 Bug（错误）消失',
      takeaway: '质量目标不应是幻想零错误，而是控制错误进入用户环境的概率和影响。',
      beginner: '人会写错，机器也会根据不完整信息做错。真正可靠的工厂不是从不出错，而是有多道检查和停止机制。',
      example: '主持人提出传统情况写代码一天、修 Bug（错误）三天的问题，追问新流程如何避免维护时间吞掉开发速度。',
      principle: '人工代码和人工智能代码都可能包含需求理解、边界处理、并发和依赖错误。Harness（驾驭系统）负责让错误可见、可分流、可恢复。',
      misconception: '不能用“错误不可避免”为低质量开脱。不可避免的是存在概率，不代表可以省略测试、监控或责任。',
      extension: '质量工程常用风险思维：错误概率乘以影响程度。低概率但灾难性的问题仍值得投入大量预防。',
      terms: ['coding', 'harness-engineering', 'reliable'],
      check: check('c3-q1', 'c3-bugs-inevitable', '更合理的质量目标是什么？', ['保证永远零错误', '控制错误概率和影响', '发布后再说'], 1, '可靠系统通过多层机制降低发生概率并限制影响。'),
    },
    {
      id: 'c3-pre-release', source: { start: 1173.6, end: 1218.41, speakers: [2] },
      title: '第一道防线：发布前阻止已知问题进入生产环境',
      takeaway: '集成和测试阶段用回归测试检查旧能力是否被新改动破坏。',
      beginner: '修好一扇门后，还要确认没有把旁边窗户弄坏。回归测试就是重新检查原来应该正常的部分。',
      example: '节目提到在 Integration（集成）和 Testing（测试）阶段运行 Regression Test（回归测试），避免 Bug（错误）进入 Production（生产环境）并破坏系统。',
      principle: '发布前测试适合稳定复现的要求。它把过去出现过的问题和关键业务规则变成自动检查，形成最低质量基线。',
      misconception: '回归测试通过不等于系统没有未知问题。测试只能证明检查过的条件，不证明所有现实组合。',
      extension: '高价值回归用例通常来自历史事故、核心路径和高风险边界，而不是盲目追求测试数量。',
      terms: ['regression-test', 'production', 'integration-test'],
      check: check('c3-q2', 'c3-pre-release', '回归测试主要防什么？', ['新改动破坏旧功能', '市场需求变化', '用户忘记密码'], 0, '它重新验证已有行为在改动后仍然成立。'),
    },
    {
      id: 'c3-post-release', source: { start: 1218.41, end: 1246.42, speakers: [2] },
      title: '第二道防线：未知问题发布后要尽快被识别',
      takeaway: '边界情况和并发错误可能绕过测试，重点变成缩短发现、定位和修复时间。',
      beginner: '消防演习无法覆盖每一种真实火情，所以大楼还需要烟雾报警、疏散和应急队伍。',
      example: '节目列举 Corner Case（边界情况）和 Race Condition（竞态条件），说明有些问题只有真实流量与特殊时序下才出现。',
      principle: '发布后依靠日志、指标、用户反馈和事故检测发现异常，再把事件送入分诊和修复流程。',
      misconception: '发布后监控不是测试失败后的补救，而是质量体系本来就应包含的一层。',
      extension: '常见可靠性指标包括平均发现时间和平均恢复时间，它们分别衡量看见问题与恢复服务的速度。',
      terms: ['corner-case', 'race-condition', 'log', 'incident'],
      check: check('c3-q3', 'c3-post-release', '竞态条件为什么难在测试中完全覆盖？', ['与操作时序组合有关', '只发生在纸上', '没有任何影响'], 0, '并发先后顺序数量很多，真实环境更容易触发少见组合。'),
    },
    {
      id: 'c3-parallel-triage', source: { start: 1246.42, end: 1287.09, speakers: [1, 2] },
      title: '多个 Agent（智能体）并行找问题，改变的是响应速度',
      takeaway: '前端、后端和核心系统可由不同智能体同时监测，避免所有问题排在一条人工队列中。',
      beginner: '医院分诊不会让一位医生依次检查所有人，而是先分类，再让不同科室同时处理。',
      example: '节目案例中多个 Agent（智能体）分别识别前端、后端和核心错误，发现可能用一两分钟，分配只需几秒，完整周期约一两小时。',
      principle: 'Parallel（并行）监测提高吞吐量，Bug Triage（错误分诊）根据类型、风险和责任范围把问题送到合适处理者。',
      misconception: '并行数量越多不一定越快。重复报警、冲突修复和共享资源竞争会产生新的协调成本。',
      extension: '分诊系统需要去重、优先级和升级规则，否则大量低价值告警会淹没真正危险的问题。',
      terms: ['parallel', 'bug-triage', 'agent'],
      check: check('c3-q4', 'c3-parallel-triage', '分诊的核心作用是什么？', ['把所有问题随机分配', '按类型和风险送到合适流程', '只处理界面问题'], 1, '分类和优先级让不同问题进入对应处理路径。'),
    },
    {
      id: 'c3-two-backlogs', source: { start: 1287.09, end: 1318.57, speakers: [4] },
      title: '功能清单与错误清单为什么长期争夺资源',
      takeaway: '传统团队常在“做新能力”和“修旧问题”之间拉扯，因为两类工作共享有限工程时间。',
      beginner: '一家小店只有一名师傅，要么做新菜单，要么修坏掉的冰箱，每次选择都会让另一边等待。',
      example: '节目描述过去有很长的 Feature Wish List（功能愿望清单）和 Bug List（错误清单），市场、产品和工程反复争论先做哪一个。',
      principle: '当实现和修复速度提高，两条队列都可能缩短，但优先级问题不会彻底消失，只是转移到市场选择和风险判断。',
      misconception: '清单消失不代表需求和错误消失。更可能是它们被系统自动处理、动态排序或隐藏在新的工作流中。',
      extension: '观察队列长度还不够，应同时看等待时间、完成价值和积压是否反复出现。',
      terms: ['feature', 'bug-triage', 'topline-metrics'],
      check: check('c3-q5', 'c3-two-backlogs', '两条清单过去为什么冲突？', ['共享有限工程资源', '名字不同', '不能记录文字'], 0, '新功能和修复都需要同一批人投入时间。'),
    },
    {
      id: 'c3-autofixing', source: { start: 1318.57, end: 1351.31, speakers: [2] },
      title: '节目中的 50% 自动修复，是风险分层后的结果',
      takeaway: '系统只对低敏感目录中的问题自动提交修复，高风险区域仍需要更严格的人审。',
      beginner: '自动售货机可以自行补报普通缺货，但金库钥匙异常必须通知负责人，不能按同一规则处理。',
      example: '节目案例称 50% 以上 Issue（问题）通过 Autofixing（自动修复）处理：人工智能提交 Pull Request（代码合并请求），工程师简单批准后发布。',
      principle: '自动化范围由代码位置、权限、潜在影响和可回退性决定。低风险路径追求速度，高风险路径保留更多审查。',
      misconception: '50% 是特定系统的节目自述，不代表任何公司都应达到同一比例，也不代表这些问题完全没有人工参与。',
      extension: '自动修复最适合可重复验证、影响范围小、回退简单的问题，例如样式、文案或局部配置。',
      terms: ['autofixing', 'pull-request', 'production'],
      check: check('c3-q6', 'c3-autofixing', '自动修复适合什么问题？', ['低风险且容易验证的问题', '所有安全权限问题', '无法回退的问题'], 0, '可验证和可回退降低了自动处理的后果。'),
    },
    {
      id: 'c3-sensitive-review', source: { start: 1351.31, end: 1373.91, speakers: [1, 2] },
      title: '触碰安全和 Agent Behavior（智能体行为）时必须升级审核',
      takeaway: '同样是几行代码，修改认证或行为核心的风险远高于调整普通界面。',
      beginner: '改餐厅菜单字体和改燃气阀门都可能只动一个零件，但后者出错会造成完全不同的后果。',
      example: '节目把涉及 Security（安全）或 Agent Behavior（智能体行为）的修复交给专门响应人员做更深入 Review（审核）。',
      principle: '风险由潜在影响而不是改动行数决定。敏感系统需要额外证据、双人审核、隔离验证和明确回退方案。',
      misconception: '人工深度审核也不是绝对安全。审核者可能遗漏问题，因此还需要自动测试、权限隔离和上线监控。',
      extension: '高风险变更常使用职责分离：提出修改、批准修改和执行发布由不同身份完成。',
      terms: ['review', 'authentication', 'sandbox'],
      check: check('c3-q7', 'c3-sensitive-review', '为什么安全修改要升级审核？', ['因为代码一定更长', '因为潜在影响更严重', '因为界面不好看'], 1, '风险取决于失败后果和影响范围。'),
    },
    {
      id: 'c3-error-taxonomy', source: { start: 1373.91, end: 1415.16, speakers: [1, 2] },
      title: 'Agent Behavior（智能体行为）错误不只指价值观',
      takeaway: '成本过高、延迟过长、幻觉、工具认证失败和任务无法完成，都属于行为层问题。',
      beginner: '配送员没有恶意，但走错路线、花费过高、迟到或无法进入小区，仍然意味着服务失败。',
      example: '节目把 Cost（成本）、Latency（延迟）、Hallucination（幻觉）、Tool Authentication（工具认证）和任务失败都列入行为问题。',
      principle: '行为是系统对输入和环境产生的可观察结果。评价不能只看答案文本，还要看工具、时间、费用和完成状态。',
      misconception: '不要只用“是否完成”作为唯一指标。任务完成但成本失控、权限违规或结果不可靠，同样不可接受。',
      extension: '行为评估可以分成有效性、效率、安全性和可解释性四个维度，避免单指标优化。',
      terms: ['latency', 'hallucination', 'authentication', 'reliable'],
      check: check('c3-q8', 'c3-error-taxonomy', '任务完成但成本失控算成功吗？', ['算，因为完成了', '不算，效率也是约束'], 1, '系统目标通常包含成本、速度和安全等多重条件。'),
    },
    {
      id: 'c3-reliable-cost', source: { start: 1415.16, end: 1461.49, speakers: [1, 2] },
      title: '优化目标是在较低成本下可靠完成，而不是追求单次完美',
      takeaway: '质量、成本和速度需要一起权衡，不能只把一种指标拉到最高。',
      beginner: '每次寄快递都用私人飞机可能很快很稳，但成本让服务无法持续；只选最便宜又可能频繁丢件。',
      example: '嘉宾将目标描述为在 Cost（成本）尽量低的情况下 Reliable（可靠）地完成用户 Task（任务）。',
      principle: '系统设计是在约束下优化：达到足够质量，同时控制资源、等待和风险。不同任务应有不同服务等级。',
      misconception: '最低成本不是绝对目标。对医疗、安全和资金等高风险任务，增加验证成本往往合理。',
      extension: '可以为任务定义预算：允许多少工具调用、最长等待多久、最低正确率和哪些条件必须人工确认。',
      terms: ['reliable', 'latency', 'review'],
      check: check('c3-q9', 'c3-reliable-cost', '系统优化为什么需要多个指标？', ['因为单指标会牺牲其他重要目标', '因为数字越多越专业', '为了让界面更复杂'], 0, '只追求速度或成本都可能伤害质量与安全。'),
    },
    {
      id: 'c3-architect-operator', source: { start: 1461.49, end: 1535.36, speakers: [1, 2] },
      title: 'Architecture（架构者）与 Operator（操作者）承担不同责任',
      takeaway: '人工智能可以给出局部方案，但系统边界、安全和延迟仍需要架构判断。',
      beginner: '装修工能按图施工，建筑师要决定承重、逃生和管线。两类工作都重要，但判断范围不同。',
      example: '节目用 Sandbox（沙箱）与 Host（宿主系统）的交互说明架构职责：AI Coding（人工智能编程）可能给出可运行方案，却留下安全或延迟隐患。',
      principle: 'Architecture（架构者）定义系统结构、原则和风险边界；Operator（操作者）在结构内运行、维护和处理日常任务。',
      misconception: '架构者不是只画图不落地。架构判断必须通过真实运行、测量和故障反馈不断校正。',
      extension: '架构决策常影响很久，因此应记录为什么选择、有哪些替代方案，以及未来在什么条件下重新评估。',
      terms: ['architecture', 'operator', 'sandbox', 'coding'],
      check: check('c3-q10', 'c3-architect-operator', '谁主要决定沙箱和宿主系统的安全边界？', ['架构者', '随机用户', '只看生成速度'], 0, '跨组件边界和长期风险属于架构判断。'),
    },
    {
      id: 'c3-team-size', source: { start: 1535.36, end: 1548, speakers: [1, 2] },
      title: '团队规模数字说明杠杆，不证明一个人能长期包办所有工作',
      takeaway: '节目认为过去需要 10 到 20 人的搭建工作，可能由一名架构者在一周内完成主体。',
      beginner: '大型机械能让一人完成过去多人搬运，但设备维护、安全检查和后续运营仍需要合适组织。',
      example: 'Peter（彼得）说自己先架构系统并向团队 Demonstrate（展示）新方案在效率和成本上的优势。',
      principle: '人工智能降低实现和试验成本，使资深判断能够产生更大杠杆；长期产品仍涉及运营、市场、支持和责任。',
      misconception: '不能把节目中的一周和一人外推为所有项目标准。系统复杂度、合规要求和已有技术债都会改变投入。',
      extension: '更好的比较单位是完成相同范围与质量需要多少总投入，而不是只比较某个阶段的人数。',
      terms: ['architecture', 'ai-first', 'deployment'],
      check: check('c3-q11', 'c3-team-size', '团队规模案例最合理的理解是什么？', ['人工智能放大架构判断的杠杆', '所有公司只需一人', '运营工作消失'], 0, '它说明特定搭建阶段的杠杆变化，不是普遍组织公式。'),
    },
    {
      id: 'c3-system-not-intelligence', source: { start: 1548, end: 1590.29, speakers: [4] },
      title: '发生错误时，先问系统缺了什么，而不是只纠正这次回答',
      takeaway: '把人工智能当系统看待，会从一次输出错误追到数据、工具、规则和评估机制。',
      beginner: '学生总在同一类题上犯错，老师不应只改这一题，还要检查概念、练习方式和反馈是否有缺口。',
      example: '节目强调不要只想着纠正 Intelligence（智能）本身，而要修补支撑它工作的 System（系统）。',
      principle: '一次错误可能来自输入、知识、权限、工具、环境或目标。系统分析寻找可重复的原因，并设计以后能自动防止或发现的机制。',
      misconception: '系统视角不代表忽略具体错误。具体错误仍要止损，只是处理结束后还要追问为什么会发生。',
      extension: '事故复盘常区分直接原因和系统原因：直接原因解释这次发生什么，系统原因解释为什么防线没有挡住。',
      terms: ['harness-engineering', 'feedback', 'self-healing'],
      check: check('c3-q12', 'c3-system-not-intelligence', '重复错误最值得增加什么？', ['只改当前输出', '系统层防线和反馈', '更长等待'], 1, '系统层改进能减少同类问题再次出现。'),
    },
    {
      id: 'c3-dynamic-growth', source: { start: 1590.29, end: 1642.66, speakers: [4] },
      title: '动态 Harness（驾驭系统）像训练，而不是固定枷锁',
      takeaway: '系统需要规则内的成长空间，根据错误和结果不断改变，而不是永远执行同一套限制。',
      beginner: '教孩子过马路不是永远牵着不让动，而是建立规则、陪同练习、观察错误，逐渐增加独立性。',
      example: '嘉宾把 Harness（驾驭系统）比作提供培训师：发现错误后不只代替修改，还帮助系统学会下一次怎么做。',
      principle: '动态规则会根据能力、风险和证据调整权限与自主程度。成长和约束形成同一个控制过程。',
      misconception: '成长空间不是无限权限。权限扩大应以持续表现、可观察性和可回退能力为条件。',
      extension: '分级授权可以把任务按风险分层：低风险自动执行，中风险先预览，高风险必须批准。',
      terms: ['harness-engineering', 'self-improvement', 'feedback'],
      check: check('c3-q13', 'c3-dynamic-growth', '动态规则为什么会变化？', ['根据能力和风险证据调整', '为了随机制造惊喜', '因为不需要安全'], 0, '权限与自主程度应随可靠证据变化。'),
    },
    {
      id: 'c3-future-consumer', source: { start: 1642.66, end: 1689.81, speakers: [1, 4] },
      title: '工作结果的消费者改变，质量标准也可能改变',
      takeaway: '未来文章、图片或接口可能先被 Agent（智能体）读取，人类审美不再是唯一评价入口。',
      beginner: '给人看的地图强调视觉清楚，给导航程序的数据强调坐标结构。两者都传递路线，但最佳形式不同。',
      example: '节目提出未来内容受众未必是人；某些对人很刺眼的格式问题，对机器读取可能并不致命。',
      principle: '质量标准应来自消费者任务。面向人关注理解、信任与体验，面向系统关注结构、准确、可解析和权限。',
      misconception: '机器先读不等于可以忽视人。最终利益相关者、品牌责任和监管通常仍由人承担。',
      extension: '同一内容可以提供人类界面和机器接口两种表达，各自优化但共享事实来源。',
      terms: ['agent', 'api', 'reliable'],
      check: check('c3-q14', 'c3-future-consumer', '质量标准为什么会随消费者改变？', ['不同消费者完成任务的方式不同', '质量不再重要', '人永远不看内容'], 0, '人和系统对格式、结构和体验的要求不同。'),
    },
    {
      id: 'c3-reframe-problem', source: { start: 1689.81, end: 1710.04, speakers: [1, 4] },
      title: '修复前先确认：这件事现在仍然是问题吗',
      takeaway: '价值判断变化时，过去的缺陷可能不再重要，也可能出现过去没有的新风险。',
      beginner: '纸质报纸折痕很严重，但电子阅读器根本没有折痕问题；与此同时，它会新增电量和隐私问题。',
      example: '节目从“彻底修复单个问题”推进到“重新判断问题定义”，要求根据实际消费者与市场结果更新标准。',
      principle: '问题不是脱离目标独立存在的。只有明确谁受影响、影响什么目标、代价多大，才能决定是否修复。',
      misconception: '重新定义问题不能成为忽略缺陷的借口。必须用用户、业务和风险证据说明为什么优先级改变。',
      extension: '需求管理中常用机会成本：修一个问题意味着暂时不做另一件事，因此要比较相对价值。',
      terms: ['product-sense', 'topline-metrics', 'review'],
      check: check('c3-q15', 'c3-reframe-problem', '重新判断问题需要什么依据？', ['消费者目标和实际影响', '开发者个人喜好', '随机选择'], 0, '问题优先级由目标、影响和代价决定。'),
    },
    {
      id: 'c3-agent-reads-assets', source: { start: 1710.04, end: 1733.72, speakers: [4] },
      title: '营销素材可能同时服务人类与 Agent（智能体）',
      takeaway: '一个素材在人类审美上普通，却可能因结构清晰而被智能体更好理解和推荐。',
      beginner: '商品包装吸引人类，结构化商品参数帮助比价程序。两种表达可能影响同一次购买。',
      example: '嘉宾提到 Go to Market Assets（市场素材）由人主观看可能不够好，投向市场后却可能得到更好数据反馈。',
      principle: '评价应区分人类体验指标和机器可读指标，再观察它们如何共同影响最终转化。',
      misconception: '数据更好不代表素材一定更有长期价值。短期点击可能伤害信任、品牌或后续留存。',
      extension: '可以为同一事实建立结构化数据层，再生成适合不同消费者的表现层，减少内容互相矛盾。',
      terms: ['go-to-market', 'agent', 'ab-test'],
      check: check('c3-q16', 'c3-agent-reads-assets', '为什么素材需要双重评价？', ['人和智能体读取方式不同', '为了增加文件', '因为审美不存在'], 0, '不同消费者需要不同表达，但最终应连接同一价值目标。'),
    },
    {
      id: 'c3-agent-economy', source: { start: 1733.72, end: 1772.29, speakers: [1, 4] },
      title: 'Agent Economy（智能体经济）从“帮我看”开始进入购买链',
      takeaway: '智能体可以先搜索、筛选和比较，再把少量候选交给人，已经影响谁获得注意力。',
      beginner: '过去你自己逛十家店，现在请助手先挑三家。商家首先要让助手理解，才有机会被你看到。',
      example: '节目设想订报纸、订牛奶和购买决策由 Agent（智能体）完成，并指出许多人已经让智能体先读文章和视频。',
      principle: '智能体成为信息中介后，会根据可访问数据、规则和偏好筛选候选。内容是否能被正确解析会影响市场机会。',
      misconception: '智能体推荐不一定中立。训练数据、商业合作、权限和用户配置都可能造成偏差。',
      extension: '未来的搜索优化可能同时面向人类信任和智能体可验证性，例如来源、结构化参数与可追溯证据。',
      terms: ['agent-economy', 'agent', 'go-to-market'],
      check: check('c3-q17', 'c3-agent-economy', '智能体作为信息中介改变了什么？', ['谁先获得注意力', '商品不再需要质量', '人类完全消失'], 0, '筛选入口改变会影响哪些选项进入人的视野。'),
    },
    {
      id: 'c3-compliance-example', source: { start: 1772.29, end: 1827.55, speakers: [1, 4] },
      title: '合规服务调研展示了智能体筛选的现实路径',
      takeaway: '智能体先研究供应商，人再复核候选；随着能力提高，第二层和第三层筛选也可能自动化。',
      beginner: '你不再从所有医生中自己搜索，而是先让助手按资质、地点和价格筛一轮，再看少量候选。',
      example: '嘉宾寻找 SOC（服务组织控制）2 型认证和 ISO（国际标准化组织标准）服务公司时，先让 Agent（智能体）Research（调研），再阅读结果。',
      principle: '智能体将公开信息转换为比较结果，因此供应商需要提供清晰、可信、可验证的数据，而不仅是吸引人的页面。',
      misconception: '第一轮筛选方便不代表可以直接签约。合规、合同和责任仍需要核验原始证据与专业意见。',
      extension: '高风险采购可以让智能体负责搜集和整理，人负责核实资质、利益冲突和最终责任。',
      terms: ['agent', 'review', 'reliable'],
      check: check('c3-q18', 'c3-compliance-example', '智能体在高风险采购中更适合先做什么？', ['搜集和整理候选', '未经核验直接签约', '隐藏原始来源'], 0, '先扩大信息处理能力，再由人核验关键证据。'),
    },
    {
      id: 'c3-saas-interface', source: { start: 1827.55, end: 1866.98, speakers: [1, 2] },
      title: 'SaaS（软件即服务）从给人看的 Dashboard（仪表盘）转向给 Agent（智能体）的接口',
      takeaway: '当智能体管理任务，产品价值会从漂亮界面部分转移到可调用、可授权和可观察的接口。',
      beginner: '人去仓库需要清楚的货架标识，机器人去仓库更需要标准坐标、接口和权限，两套入口可以同时存在。',
      example: '节目以 Asana（任务管理产品）和 Linear（研发管理产品）类产品为例，团队更关心是否提供良好的 MCP（模型上下文协议）与 API（应用程序接口）。',
      principle: 'Dashboard（仪表盘）服务人的浏览和操作；MCP（模型上下文协议）与 API（应用程序接口）服务系统读取、排序和执行。未来产品要同时处理身份、权限和可追踪性。',
      misconception: '接口重要不代表界面会消失。人仍需要设置目标、处理例外、理解状态和承担责任。',
      extension: '面向智能体的产品设计需要机器可读文档、稳定契约、细粒度权限、调用限额和审计日志。',
      terms: ['saas', 'dashboard', 'mcp', 'api', 'authentication'],
      check: check('c3-q19', 'c3-saas-interface', '智能体使用任务产品最需要什么？', ['稳定接口与权限', '只需要动画', '完全隐藏状态'], 0, '机器调用依赖清晰契约、身份和权限控制。'),
    },
  ],
  quiz: [
    check('c3-quiz-1', 'c3-pre-release', '发布前回归测试通过是否证明零风险？', ['证明', '不证明，只覆盖已检查条件'], 1, '未知边界和真实环境问题仍可能出现。'),
    check('c3-quiz-2', 'c3-parallel-triage', '并行智能体的新风险是什么？', ['重复告警与冲突修复', '速度一定更慢', '没有任何风险'], 0, '并行需要去重和协调。'),
    check('c3-quiz-3', 'c3-autofixing', '自动修复比例应由什么决定？', ['风险和可验证性', '追求统一数字', '代码颜色'], 0, '低风险、可回退问题更适合自动化。'),
    check('c3-quiz-4', 'c3-system-not-intelligence', '系统视角如何处理重复错误？', ['只改一次输出', '增加以后可复用的防线'], 1, '根因与反馈机制能减少同类问题。'),
    check('c3-quiz-5', 'c3-agent-economy', '智能体经济首先改变什么？', ['信息筛选入口', '所有责任归零', '产品无需数据'], 0, '谁能被智能体理解和推荐，会影响市场注意力。'),
    check('c3-quiz-6', 'c3-saas-interface', '为什么接口价值上升？', ['智能体需要稳定调用产品能力', '人类不再存在', '界面不能展示数据'], 0, '智能体通过机器接口读取和执行任务。'),
    check('c3-quiz-7', 'c3-reliable-cost', '高风险任务是否应永远选最低成本？', ['是', '否，应为验证与安全投入'], 1, '风险后果会改变合理成本。'),
    check('c3-quiz-8', 'c3-sensitive-review', '敏感改动为什么不能只看代码行数？', ['影响范围更重要', '行数无法统计', '所有代码相同'], 0, '少量权限代码也可能产生重大后果。'),
  ],
}
