import type { Chapter, QuizQuestion } from '../types'

const check = (id: string, unitId: string, prompt: string, options: string[], answer: number, explanation: string): QuizQuestion => ({ id, unitId, prompt, options, answer, explanation })

export const chapter6: Chapter = {
  id: 'chapter-6', number: 6, title: '组织结构与角色融合', source: { start: 2867.96, end: 3201.18 },
  objectives: ['理解组织从信任人到信任系统需要哪些 Guardrails（护栏规则）。', '分清产品经理岗位、产品判断能力和团队产品职责三个概念。', '能重新分配价值定义、信号收集、实现和审核职责，并解释对齐成本。'],
  interaction: { id: 'org-workbench', kind: 'organization', title: '组织责任工作台', description: '把关键职责分配给单独角色、跨职能团队或人工智能系统，观察信任和对齐成本。' },
  recap: '角色边界会融合，但价值定义、工程可靠性和最终责任不会因为岗位名称变化而自动消失。',
  next: '下一章继续追问人才：初级与资深工程师各有什么优势，未来最稀缺的能力组合是什么。',
  units: [
    {
      id: 'c6-whole-picture', source: { start: 2867.96, end: 2880.56, speakers: [1] },
      title: '先看 Whole Picture（全貌），组织变化才不会变成零散岗位新闻',
      takeaway: '单个案例只能说明局部效率，完整组织图还要解释信任、决策、职责和协作怎样一起变化。',
      beginner: '只知道餐厅少了一个传菜员，无法判断整体效率；还要看点单、厨房、出餐和顾客反馈如何连接。',
      example: '主持人要求嘉宾把前面产品、市场和工程案例合成一幅 Whole Picture（全貌），比较传统与新组织结构。',
      principle: '组织设计关注工作如何流动、谁拥有信息、谁做决定、谁承担后果，而不只是岗位数量。',
      misconception: '少一个岗位不一定代表职责消失，职责可能转移、自动化或由团队共同承担。',
      extension: '画组织图时同时画信息流和决策流，比只画汇报关系更能解释真实工作。',
      terms: ['workflow', 'alignment', 'review'],
      check: check('c6-q1', 'c6-whole-picture', '组织全貌最需要包含什么？', ['信息、决策和责任流', '只看人数', '只看职位名称'], 0, '工作如何流动比岗位名称更重要。'),
    },
    {
      id: 'c6-trust-shift', source: { start: 2880.56, end: 2921.51, speakers: [3] },
      title: '第一层变化：从信任个人，转向信任有边界的人工智能系统',
      takeaway: '组织必须知道人工智能为什么可以做决定、能做什么、失败后谁介入，才能把任务真正交出去。',
      beginner: '信任自动扶梯不是因为它“聪明”，而是因为有设计标准、检测、停止按钮和维护责任。',
      example: '嘉宾把 Planning（规划）、Execution（执行）和决策都纳入信任问题，并强调需要 Guardrails（护栏规则）和机制保障。',
      principle: '系统信任来自可预测行为、权限边界、证据、监控、人工升级和责任归属，不是来自一句“模型很强”。',
      misconception: '信任人工智能不等于相信每次输出。它更像相信一套能发现和处理错误的制度。',
      extension: '可以把信任拆成能力、诚实、可控和可恢复四个维度，分别设计证据。',
      terms: ['guardrails', 'planning', 'execution', 'review'],
      check: check('c6-q2', 'c6-trust-shift', '系统信任主要来自什么？', ['可验证机制和责任边界', '模型名称', '完全不出错'], 0, '组织信任的是可控制和可恢复的系统。'),
    },
    {
      id: 'c6-pm-distributed', source: { start: 2921.51, end: 2948, speakers: [3] },
      title: '产品经理职责可以分散到工程师和工程管理者',
      takeaway: '开发成本下降后，理解用户、选择问题和观察结果可以由更多直接实现的人承担。',
      beginner: '过去由一人写菜谱再交给厨师，现在厨师也能快速试菜，就可以直接参与菜单判断。',
      example: '嘉宾说公司并非没有产品经理能力，而是把职责拆到每个工程师和 Peter（彼得）这样的工程管理者身上。',
      principle: '职责分散减少交接，但要求工程人员具备产品感、数据能力和发布后责任。',
      misconception: '工程师能实现不代表自动理解用户。没有研究和价值判断，快速实现只会加速错误方向。',
      extension: '分散职责需要共同原则和数据，否则不同工程师会形成互相冲突的产品方向。',
      terms: ['product-manager', 'product-sense', 'implementation'],
      check: check('c6-q3', 'c6-pm-distributed', '职责分散的新要求是什么？', ['实现者也承担产品判断', '取消用户研究', '所有人各做各的'], 0, '交接减少后，实现者要理解价值和结果。'),
    },
    {
      id: 'c6-pm-conflict', source: { start: 2948, end: 2975.29, speakers: [3] },
      title: '产品经理常成为矛盾集中点，因为同时连接市场和开发',
      takeaway: '角色本身不是问题，问题是大量信息翻译和对齐都压在一个人身上。',
      beginner: '所有部门都通过同一个翻译沟通，这个人很重要，也会成为等待和误解的瓶颈。',
      example: '节目认为 Product Manager（产品经理）常集中市场、产品和工程之间的 Alignment（对齐）成本。',
      principle: '中介角色能减少双方直接沟通，但会形成单点瓶颈。共享数据和系统状态可以替代部分机械翻译。',
      misconception: '拿掉中介不会自动降低成本。如果团队缺乏共同语言，冲突会分散到更多人之间。',
      extension: '判断是否需要中介角色，应比较减少的协调成本与新增的等待、失真和责任模糊。',
      terms: ['product-manager', 'alignment', 'workflow'],
      check: check('c6-q4', 'c6-pm-conflict', '产品经理为何容易成为瓶颈？', ['大量信息和决策经过一处', '职位名称太长', '不能使用数据'], 0, '集中协调既有价值也有限制。'),
    },
    {
      id: 'c6-pm-value-question', source: { start: 2975.29, end: 2984.57, speakers: [1] },
      title: '“未来还需要产品经理吗”其实包含三个不同问题',
      takeaway: '要分开问岗位是否存在、产品判断是否需要、哪些人承担这些职责。',
      beginner: '“还需要司机吗”可以指职业名称、驾驶能力或谁负责安全，三种问题答案可能不同。',
      example: '主持人追问产品经理角色还有没有价值，以及未来招聘类似角色需要什么新技能。',
      principle: '技术会改变岗位边界，但用户需求、优先级、商业目标和结果审核仍然存在。',
      misconception: '用“需要”或“不需要”二选一，会掩盖职责重新组合的真实变化。',
      extension: '分析任何职业变化都可用“任务、能力、责任、岗位”四层框架，避免只讨论职位名称。',
      terms: ['product-manager', 'product-sense', 'generalist'],
      check: check('c6-q5', 'c6-pm-value-question', '判断岗位未来时先拆什么？', ['任务、能力和责任', '只看名称', '只看工资'], 0, '岗位可能变化，但组成任务仍需处理。'),
    },
    {
      id: 'c6-new-pm', source: { start: 2984.57, end: 3029.43, speakers: [3] },
      title: '未来需要的是新形态 Product Manager（产品经理）',
      takeaway: '开发成本降低后，产品角色更可能来自工程背景，或由开发团队共同拥有。',
      beginner: '以前画图的人和施工的人分开，工具进步后，一个人可以快速画、搭、测，再决定是否继续。',
      example: '嘉宾认为工程师可以承担产品经理职责，也可能把产品权限分散到开发团队各成员。',
      principle: '新形态产品角色需要直接实验能力、用户理解、指标判断和跨领域沟通，而不只是写 PRD（产品需求文档）。',
      misconception: '能快速做原型不等于能构建长期产品。可靠性、渠道、支持和商业模式仍需考虑。',
      extension: '产品人员可以通过低成本原型直接验证假设，把需求文档从交接材料转变为实验记录。',
      terms: ['product-manager', 'prd', 'implementation'],
      check: check('c6-q6', 'c6-new-pm', '新形态产品角色增加什么能力？', ['直接实验与实现', '只写更长文档', '不看用户'], 0, '低成本实现让产品判断更接近真实证据。'),
    },
    {
      id: 'c6-role-fusion', source: { start: 3029.43, end: 3070.74, speakers: [1, 3] },
      title: '工程师与产品经理都可能快速把想法变成产品',
      takeaway: '角色融合后，起点来自技术还是产品不再最重要，能否形成用户价值更重要。',
      beginner: '会做菜的人也能设计菜单，会设计菜单的人也能快速试做，最终要看顾客是否愿意吃。',
      example: '主持人提出两种路径：工程团队承担产品判断，或优秀产品经理借助人工智能直接实现想法。',
      principle: '人工智能降低 Implementation（实现）门槛，使想法、实现和反馈更紧密；决定优势的是判断质量和完整交付。',
      misconception: '工具降低门槛不等于专业差异消失。不同背景仍影响风险识别、用户理解和商业判断。',
      extension: '角色融合适合小团队快速探索，规模扩大后仍需要明确质量和责任所有者。',
      terms: ['implementation', 'product-sense', 'generalist'],
      check: check('c6-q7', 'c6-role-fusion', '角色融合后评价重点是什么？', ['是否形成用户价值', '原职位名称', '谁先提出想法'], 0, '结果价值比角色出身更重要。'),
    },
    {
      id: 'c6-commercialization', source: { start: 3070.74, end: 3088.5, speakers: [3] },
      title: '能 Build（构建）产品与能 Commercialize（商业化）产品仍是两件事',
      takeaway: '原型能运行后，还要解决可靠性、成本、渠道、支持和客户愿不愿付费。',
      beginner: '会烤一块好蛋糕不等于能经营连锁店，后者需要供应、质量和销售。',
      example: '嘉宾提醒没有技术背景的产品经理即使能快速构建产品，能否商业化仍需要打问号，可能仍需工程师完善。',
      principle: 'Commercialization（商业化）要求产品在规模、成本和责任上可持续，不能只靠一次演示。',
      misconception: '工程师参与也不自动保证商业化。没有客户需求和市场渠道，技术质量无法单独创造业务。',
      extension: '从原型到商业化可检查可靠、可卖、可支持、可合规和可盈利五个条件。',
      terms: ['commercialization', 'reliable', 'go-to-market'],
      check: check('c6-q8', 'c6-commercialization', '原型到商业化新增什么？', ['规模化与持续经营条件', '只增加动画', '取消用户'], 0, '商业化要求完整业务系统。'),
    },
    {
      id: 'c6-team-product-role', source: { start: 3088.5, end: 3120.4, speakers: [3] },
      title: '产品经理角色可能从个人英雄转向团队共同能力',
      takeaway: '市场、设计、工程和数据共同承担产品判断，组织整体而非某个明星人物形成结果。',
      beginner: '球队不只靠一名队长得分，战术、传球、防守和训练共同决定比赛。',
      example: '嘉宾认为未来可能不是一个人担任 Product Manager（产品经理），而是团队整体扮演产品角色。',
      principle: '组织化产品能力需要共享目标、用户证据和决策记录，避免责任在“大家共同负责”中消失。',
      misconception: '团队共同负责最危险的结果是没人负责。关键决策仍应有明确 Owner（责任人）。',
      extension: '可以让建议开放给团队，但为每个目标、指标和发布指定单一责任者。',
      terms: ['product-manager', 'alignment', 'review'],
      check: check('c6-q9', 'c6-team-product-role', '团队共同承担产品职责还需要什么？', ['明确目标与责任人', '取消所有记录', '每人独立决策'], 0, '共享能力不等于责任模糊。'),
    },
    {
      id: 'c6-generalists', source: { start: 3120.4, end: 3164.96, speakers: [2] },
      title: 'Generalist（复合型人才）在人工智能环境中更容易放大价值',
      takeaway: '工程、产品、市场和实现能力组合在一起，可以减少想法在角色之间传递。',
      beginner: '一个人能拍摄、剪辑和发布短视频，就能快速验证内容，而不必等待三支队伍排期。',
      example: '节目认为具有 Product Sense（产品感）和 Marketing Sense（市场感）的工程师，或具有 Implementation（实现）能力的产品经理更重要。',
      principle: '人工智能降低单项执行成本后，跨领域判断和整合成为新杠杆。复合型不等于每项都最深，而是能连接完整结果。',
      misconception: '复合型不应变成一人无限加班。组织仍需通过系统和专长支持控制认知负担。',
      extension: '可以用主专长加两项邻近能力构建个人成长路线，比要求所有能力平均更现实。',
      terms: ['generalist', 'product-sense', 'implementation'],
      check: check('c6-q10', 'c6-generalists', '复合型人才的核心优势是什么？', ['跨领域连接完整结果', '每项都是世界第一', '不需要团队'], 0, '减少交接并保持端到端判断是主要价值。'),
    },
    {
      id: 'c6-designers-implement', source: { start: 3164.96, end: 3186.44, speakers: [2] },
      title: 'UX Designer（用户体验设计师）和 UI Designer（界面设计师）也需要实现能力',
      takeaway: '设计价值不仅是提供图片，而是把交互想法快速放进真实产品并观察用户反应。',
      beginner: '舞台设计师如果能快速搭出可走动模型，就能发现纸上看不到的动线问题。',
      example: '嘉宾认为未来设计角色很重要，但指的是能够 Coding（编写代码）或 Implementation（实现）想法的设计师。',
      principle: '可运行原型保留交互状态、响应式和真实内容，比静态图更接近用户体验证据。',
      misconception: '实现能力不代表设计师必须独立维护生产系统。应与工程规范、组件库和审核流程连接。',
      extension: '设计系统能让设计师使用稳定组件快速试验，同时避免每次从零构建。',
      terms: ['ux-designer', 'ui-designer', 'coding', 'implementation'],
      check: check('c6-q11', 'c6-designers-implement', '可运行原型比静态图多验证什么？', ['真实交互和状态', '只验证颜色', '取消响应式'], 0, '用户流程需要在实际操作中观察。'),
    },
    {
      id: 'c6-communication-cost', source: { start: 3186.44, end: 3201.18, speakers: [2] },
      title: '当实现只需一两小时，Communication（沟通）可能比 Implementation（实现）更贵',
      takeaway: '把想法传给另一个人、等待理解和反复对齐的时间，可能超过直接做出可测试版本。',
      beginner: '写一份十页说明让别人改一个按钮，可能比自己在工具里改好并给对方看更慢。',
      example: '节目判断在人工智能工作环境中，想法传给另一个工程师的 Alignment（对齐）成本可能远大于实现成本。',
      principle: '低成本实现鼓励直接原型交流，但高风险和共享系统仍需要评审与协作，不能把速度当作跳过团队规范的理由。',
      misconception: '沟通不是浪费。目标、边界和长期维护需要沟通；应减少的是重复转述和等待。',
      extension: '用可运行原型加简短决策记录，可以同时降低表达成本并保留团队知识。',
      terms: ['implementation', 'alignment', 'workflow'],
      check: check('c6-q12', 'c6-communication-cost', '实现变便宜后应减少什么？', ['重复转述和交接等待', '所有团队讨论', '风险审核'], 0, '机械沟通可由原型和共享状态替代。'),
    },
  ],
  quiz: [
    check('c6-quiz-1', 'c6-trust-shift', '信任系统是否等于相信每次输出？', ['是', '不是，信任的是控制与恢复机制'], 1, '系统信任包含防线和责任。'),
    check('c6-quiz-2', 'c6-pm-conflict', '取消中介角色一定降低成本吗？', ['一定', '不一定，需要共享语言和系统'], 1, '否则冲突会分散到更多人。'),
    check('c6-quiz-3', 'c6-role-fusion', '角色融合后专业能力是否消失？', ['消失', '不消失，但边界改变'], 1, '风险和商业判断仍需要专业深度。'),
    check('c6-quiz-4', 'c6-commercialization', '能运行等于能商业化吗？', ['等于', '不等于，还要可卖可支持'], 1, '商业化需要持续业务系统。'),
    check('c6-quiz-5', 'c6-generalists', '复合型是否等于所有领域最深？', ['是', '不是，重点是连接完整结果'], 1, '主专长与邻近能力更现实。'),
    check('c6-quiz-6', 'c6-communication-cost', '为什么原型能降低沟通成本？', ['直接展示真实行为', '隐藏决策', '取消反馈'], 0, '运行结果比抽象描述更容易形成共同理解。'),
  ],
}
