import type { Chapter, QuizQuestion } from '../types'

const check = (id: string, unitId: string, prompt: string, options: string[], answer: number, explanation: string): QuizQuestion => ({ id, unitId, prompt, options, answer, explanation })

export const chapter5: Chapter = {
  id: 'chapter-5', number: 5, title: '市场、个人 Agent（智能体）与 SaaS（软件即服务）重构',
  source: { start: 2343.21, end: 2867.96 },
  objectives: [
    '理解工程 Evaluation（评估）与市场价值判断为什么难度不同。',
    '能为个人 Agent（智能体）配置数据 Permission（权限）、指标和人工审核点。',
    '判断中小企业、大企业和传统企业进行人工智能转型时面对的不同约束。',
  ],
  interaction: { id: 'agent-configurator', kind: 'agent', title: '个人 Agent（智能体）配置台', description: '为一家 30 人公司选择数据权限和人工审核强度，观察效率与风险如何一起变化。' },
  recap: '个人智能体的价值来自理解具体工作并持续改进，但权限、评估与人工责任必须和能力一起设计。',
  next: '下一章进入组织内部，学习产品、工程、设计和市场职责如何融合，以及产品经理能力为什么没有消失。',
  units: [
    {
      id: 'c5-gtm-agents', source: { start: 2343.21, end: 2369.24, speakers: [1] },
      title: '开发变快之后，市场团队也会寻找自己的 Agent（智能体）工作流',
      takeaway: '代码 Agent（智能体）的进展会推动内容、研究和销售流程尝试相同的系统化方法。',
      beginner: '厨房自动化后，点单、备货和配送也会开始寻找自动化，否则餐厅整体速度仍被其他环节限制。',
      example: '主持人询问 Go to Market Team（进入市场团队）是否也使用更多 Agent（智能体）生成素材并改造流程。',
      principle: '不同部门可以共享 Harness（驾驭系统）思想，但评价标准、风险和输入数据会不同，不能照搬代码流程。',
      misconception: '生成文字和图片更快不代表市场工作已经自动化，目标客户、渠道、品牌和时机仍需要判断。',
      extension: '市场工作流可拆成调研、定位、素材、投放、反馈和复盘，每一步都需要不同证据。',
      terms: ['go-to-market', 'agent', 'workflow'],
      check: check('c5-q1', 'c5-gtm-agents', '市场工作流能否直接照搬代码流程？', ['能，评价完全相同', '不能，价值判断和风险不同'], 1, '代码与市场输出的可验证性不同。'),
    },
    {
      id: 'c5-objective-subjective', source: { start: 2369.24, end: 2393.33, speakers: [4] },
      title: '工程 Evaluation（评估）较封闭，市场 Evaluation（评估）更主观',
      takeaway: '代码是否运行通常有明确检查，内容是否有价值会因人群、时机和目标不同而变化。',
      beginner: '计算题有标准答案，广告文案是否打动人却要看受众和场景。',
      example: '嘉宾说工程环境相对容易定义“做得好不好”，而写文章和视频面向人的消费群体，价值认可更主观。',
      principle: '可自动化程度受反馈清晰度影响。标准明确、结果快速的任务更容易形成闭环；主观任务需要组合定量数据和人类判断。',
      misconception: '主观不等于无法评估。可以定义受众、行为目标、品牌约束和人工评分，只是不能用单一指标概括。',
      extension: '内容评估可分成事实准确、品牌一致、用户理解和业务行动四层，减少把点击率当成全部价值。',
      terms: ['evaluation', 'performance', 'topline-metrics'],
      check: check('c5-q2', 'c5-objective-subjective', '市场评估为什么更难自动化？', ['结果受人群和时机影响', '没有任何数据', '内容不能保存'], 0, '同一内容对不同受众可能价值不同。'),
    },
    {
      id: 'c5-human-judgment', source: { start: 2393.33, end: 2437.12, speakers: [4] },
      title: '多个 Agent（智能体）先产生候选，人再做价值判断',
      takeaway: '现阶段可以让系统扩大选择空间，但在主观市场判断上保留人类筛选。',
      beginner: '助手先准备十套方案，你不必从空白开始，但仍要判断哪套适合品牌和客户。',
      example: '嘉宾说团队不会让 Agent（智能体）百分之百决策，而是比较多个结果，再由人判断市场是否 Ready（准备好）。',
      principle: '候选生成和最终决策分离，可以利用人工智能的广度，同时保留目标、责任和上下文判断。',
      misconception: '人做最终判断不代表系统没有价值。减少搜索空间和准备材料本身就能节省大量时间。',
      extension: '可以记录人选择和拒绝的理由，让系统逐渐学习组织偏好，但仍要防止偏见被固化。',
      terms: ['agent', 'review', 'feedback'],
      check: check('c5-q3', 'c5-human-judgment', '为什么保留人类最终判断？', ['主观价值和责任仍需上下文', '人工智能不能生成内容', '为了增加等待'], 0, '市场价值包含目标、品牌和时机。'),
    },
    {
      id: 'c5-wide-permissions', source: { start: 2437.12, end: 2501.35, speakers: [1, 4] },
      title: '更广数据 Access（访问）带来三秒回答，也扩大错误半径',
      takeaway: 'Agent（智能体）读取更多内部数据能减少找人做报表，但错误读取或越权会影响决策与隐私。',
      beginner: '给助手所有房间钥匙会让他办事更快，也意味着一次误操作能影响更多地方。',
      example: '节目设想每个人的 Agent（智能体）具有更多数据读写权。过去市场负责人要找工程或数据同学做表，现在可以三秒得到回答。',
      principle: 'Permission（权限）扩大提高信息可达性，同时增加误读、泄露和错误执行风险，需要身份、范围、审计与确认。',
      misconception: '开放数据不等于所有人和所有智能体拥有相同权限。权限应根据任务、角色和敏感度动态控制。',
      extension: '细粒度权限可以限制到数据字段、时间范围、操作类型和使用次数，而不只是“允许或拒绝”。',
      terms: ['permission', 'access', 'authentication', 'log'],
      check: check('c5-q4', 'c5-wide-permissions', '权限扩大最直接增加什么风险？', ['错误影响范围和数据泄露', '界面颜色改变', '员工无法提问'], 0, '更多数据和动作意味着错误半径更大。'),
    },
    {
      id: 'c5-market-awareness', source: { start: 2501.35, end: 2528.64, speakers: [2] },
      title: '市场可能不是拒绝，而是不知道这种工作方式存在',
      takeaway: '采用障碍有时来自认知和使用门槛，而不是用户明确反对。',
      beginner: '顾客不知道可以手机点餐，就不会使用；这与知道后认为不好用是不同问题。',
      example: '嘉宾认为很多 Agent（智能体）公司的 Challenge（挑战）不是市场不能接受，而是市场不了解或不会高效使用。',
      principle: 'Adoption（采用）需要发现、理解、首次成功和持续价值四步。产品必须降低设置复杂度并尽快让用户完成真实任务。',
      misconception: '不能把所有增长问题都解释为市场教育不足。产品也可能不可靠、成本太高或没有解决真实需求。',
      extension: '观察用户在哪一步流失，才能区分“不知道”“不会用”“不信任”和“没有价值”。',
      terms: ['adoption', 'agent', 'access'],
      check: check('c5-q5', 'c5-market-awareness', '用户没采用可能有哪些原因？', ['不了解、不会用或价值不足', '只有拒绝新技术一个原因'], 0, '采用链路包含多个不同障碍。'),
    },
    {
      id: 'c5-general-agent', source: { start: 2528.64, end: 2544.52, speakers: [1, 2] },
      title: '单一 General Agent（通用智能体）服务很多人，但不一定理解每个人工作',
      takeaway: '通用智能体提供广泛能力，用户专属智能体则积累具体任务、数据和偏好。',
      beginner: '公共客服能回答常见问题，私人助理更了解你的日程、习惯和长期项目。',
      example: '节目把上一阶段 General Agent（通用智能体）描述为所有用户访问同一个 Agent（智能体），能力相同但个人工作上下文有限。',
      principle: '通用能力降低入门门槛，专属配置提高任务适配。产品需要在共享基础与个人数据隔离之间取得平衡。',
      misconception: '专属智能体不一定比通用智能体更聪明，它的优势主要来自长期上下文、工具和反馈。',
      extension: '可以采用共享模型加个人记忆和工具配置，既复用基础能力又保持客户隔离。',
      terms: ['general-agent', 'agent', 'context-engineering'],
      check: check('c5-q6', 'c5-general-agent', '专属智能体的主要优势是什么？', ['理解具体工作和长期偏好', '模型参数一定更大', '不需要权限'], 0, '长期上下文和工具配置提高任务适配。'),
    },
    {
      id: 'c5-personal-agent', source: { start: 2544.52, end: 2585.71, speakers: [2] },
      title: '个人 Agent（智能体）把重复任务变成会积累经验的系统',
      takeaway: '用户不是每周重新发起同一任务，而是创建长期运行并持续改进的专属智能体。',
      beginner: '不是每周找临时工从头解释，而是培养固定同事，让他记住流程和上周反馈。',
      example: '节目用 Campaign Agent（营销活动智能体）举例：每周投放广告，并通过后台 Harness（驾驭系统）提高 Performance（表现）、降低成本。',
      principle: '长期智能体需要身份、记忆、工具、周期触发、评估与改进。单次聊天只覆盖其中很小一部分。',
      misconception: '持续学习也可能积累错误。历史记忆需要来源、过期机制和人工纠正。',
      extension: '个人智能体可把流程拆为准备、执行、监测和复盘四个阶段，每阶段设置不同权限。',
      terms: ['campaign', 'performance', 'self-improvement', 'harness-engineering'],
      check: check('c5-q7', 'c5-personal-agent', '长期智能体比每周重复提问多了什么？', ['记忆、触发和反馈闭环', '只增加名称', '取消任务目标'], 0, '长期运行需要状态和持续改进机制。'),
    },
    {
      id: 'c5-target-customers', source: { start: 2585.71, end: 2609.35, speakers: [1, 3] },
      title: '目标客户可以很广，但早期产品必须选择最容易成功的人群',
      takeaway: '创业者、个人、小企业和大企业都可能使用，早期重点却要放在决策快、约束少的场景。',
      beginner: '新餐厅可以服务所有人，但开业初期先做好附近上班族午餐，比同时满足宴会和外卖更容易。',
      example: '主持人询问产品面向大企业流程、创业者、个人独角兽还是大众；嘉宾回答都可能，但核心先看中小企业。',
      principle: '早期市场选择要平衡痛点强度、购买速度、实施难度和反馈速度。',
      misconception: '目标客户写得越宽并不代表市场越大，反而可能让产品、销售和支持无法形成清晰方案。',
      extension: '理想早期客户通常愿意试新、问题明确、能快速反馈，并能容忍产品尚不完善。',
      terms: ['go-to-market', 'adoption', 'product-sense'],
      check: check('c5-q8', 'c5-target-customers', '早期为什么要聚焦客户？', ['更快形成可重复成功', '排斥所有其他人', '减少产品价值'], 0, '聚焦能让反馈和产品迭代更一致。'),
    },
    {
      id: 'c5-smb', source: { start: 2609.35, end: 2616.5, speakers: [1, 3] },
      title: 'SMB（中小企业）是规模概念，也代表更短决策链',
      takeaway: '节目把约 30 人以内团队作为示例，强调它们更可能较早采用新工作方式。',
      beginner: '小船转向更快，但资源较少；大船资源多，却需要更多部门一起决定。',
      example: '嘉宾解释 SMB（中小企业）为 Small to Medium Business（中小型企业），并用约 30 人团队帮助听众建立直观印象。',
      principle: '企业规模影响采购、合规、数据和人员协调。人数只是近似指标，不同行业的中小企业定义并不完全相同。',
      misconception: '小企业并不自动适合人工智能转型。缺乏数据、负责人或预算同样会失败。',
      extension: '评估组织敏捷度可以看决策层级、系统复杂度和风险要求，而不只看员工人数。',
      terms: ['smb', 'adoption', 'alignment'],
      check: check('c5-q9', 'c5-smb', '中小企业常见转型优势是什么？', ['决策链较短', '永远没有合规', '数据一定更好'], 0, '较少层级通常有利于快速试点。'),
    },
    {
      id: 'c5-enterprise-obstacles', source: { start: 2616.5, end: 2661.18, speakers: [1, 3] },
      title: '传统公司也能转型，但大企业的约束更多',
      takeaway: '合规、人员、数据库和历史系统让改变更慢，不代表技术公司天然成功、传统公司天然失败。',
      beginner: '旧房可以改智能家居，但要考虑原有线路、住户和安全规范；新房可以从设计阶段预留。',
      example: '节目指出企业越大，合规和人员因素越多；历史数据库与 Legacy System（历史遗留系统）也提高迁移难度。',
      principle: '转型难度来自组织与系统耦合。可先选择低风险、数据清楚、跨部门少的流程进行试点。',
      misconception: '传统行业不等于没有适合的自动化工作。大量重复调研、文档和运营任务可能更有价值。',
      extension: '遗留系统改造可使用适配层，先提供安全接口，再逐步替换内部结构。',
      terms: ['legacy-system', 'api', 'adoption'],
      check: check('c5-q10', 'c5-enterprise-obstacles', '大企业转型为什么更慢？', ['约束与依赖更多', '员工一定不愿意', '人工智能不能运行'], 0, '合规、人员和历史系统共同增加协调。'),
    },
    {
      id: 'c5-founder-belief', source: { start: 2661.18, end: 2703.88, speakers: [1, 3] },
      title: '相信人工智能不够，还要接受旧产品架构可能不再合适',
      takeaway: '把人工智能做成一个附加功能，可能受到数据库、交互和流程结构的根本限制。',
      beginner: '在老式收音机上加一块触摸屏，不会自动变成智能手机，因为内部结构没有变化。',
      example: '嘉宾回顾 2023 年许多 SaaS（软件即服务）公司想把人工智能集成为功能，却没有检查产品架构能否承载新能力。',
      principle: '创始人需要明确转型结果可能是整体产品重构，而不只是增加入口。接受范围决定组织是否愿意投入。',
      misconception: '整体重构不是默认答案。若接口层可以安全接入并满足目标，渐进集成可能成本更低。',
      extension: '先画出现有数据流、权限和用户任务，再判断问题是局部接口还是结构性限制。',
      terms: ['saas', 'architecture', 'legacy-system'],
      check: check('c5-q11', 'c5-founder-belief', '什么时候需要考虑整体重构？', ['旧架构根本限制新能力', '每次增加按钮', '为了追赶潮流'], 0, '结构性约束无法靠表面功能解决。'),
    },
    {
      id: 'c5-productized-harness', source: { start: 2703.88, end: 2742.2, speakers: [1, 3] },
      title: '先把 Harness（驾驭系统）做成产品，再让客户逐渐改变组织',
      takeaway: '供应商自己进行组织实验，不等于要求所有客户第一天复制同样结构。',
      beginner: '健身教练先提供可执行训练计划，让用户体验效果，再逐步改变生活习惯，而不是第一天重做全部生活。',
      example: '嘉宾说组织变革是公司自己的实践，对客户则把 Harness（驾驭系统）产品化，让用户先体验并慢慢思考组织变化。',
      principle: '产品可以降低试验门槛，把复杂基础设施封装为可用能力。客户在获得价值后更容易接受流程变化。',
      misconception: '产品体验不能替代组织责任。涉及权限、目标和绩效的改变仍需要管理者参与。',
      extension: '渐进采用可从单任务、单团队、跨团队到组织级逐步扩大，每阶段设置成功门槛。',
      terms: ['harness-engineering', 'adoption', 'workflow'],
      check: check('c5-q12', 'c5-productized-harness', '为什么先产品化？', ['降低客户试验门槛', '隐藏所有风险', '强迫组织重构'], 0, '先体验具体价值更容易推动后续改变。'),
    },
    {
      id: 'c5-domain-expertise', source: { start: 2742.2, end: 2778.53, speakers: [1, 2] },
      title: '用户要懂自己的任务，平台要懂系统工程',
      takeaway: '没有人是所有领域专家，因此要把业务判断与基础设施责任分开。',
      beginner: '医生理解诊疗目标，云平台负责服务器和安全；医生不需要自己搭数据中心。',
      example: '主持人追问只有非常懂领域才能设置精确限制的问题；嘉宾区分用户任务知识与平台架构知识。',
      principle: '业务专家定义目标、约束和质量；平台封装 Tooling（工具体系）、Security（安全）和长期运行机制。',
      misconception: '平台封装不代表用户不需要思考。目标和评价错误时，系统会高效地做错事。',
      extension: '清晰责任边界能减少“所有人都要会代码”或“平台替客户决定业务”的两个极端。',
      terms: ['tooling', 'architecture', 'evaluation'],
      check: check('c5-q13', 'c5-domain-expertise', '用户最需要提供什么？', ['任务目标和质量标准', '底层服务器代码', '平台全部权限'], 0, '业务知识决定系统应该完成什么。'),
    },
    {
      id: 'c5-cloud-abstraction', source: { start: 2778.53, end: 2824.97, speakers: [2, 3] },
      title: 'Cloud Service（云端服务）把工具接入、安全和长期运行封装起来',
      takeaway: '普通使用者不必理解全部架构，但平台必须承担隐藏复杂度带来的责任。',
      beginner: '使用网银不需要理解银行机房，但银行仍必须处理身份、审计和故障。',
      example: '嘉宾说普通用户不需要掌握 Infrastructure（基础设施），平台负责 Tooling（工具体系）接入、长期运行与安全。',
      principle: '抽象降低使用门槛。良好抽象应给用户清楚的目标设置、权限选择、状态和错误说明。',
      misconception: '看不见复杂度不代表复杂度消失。平台故障会影响很多客户，因此需要更强隔离和监控。',
      extension: '云服务可提供安全默认值，同时允许专业用户逐步解锁高级配置。',
      terms: ['cloud-service', 'tooling', 'sandbox', 'permission'],
      check: check('c5-q14', 'c5-cloud-abstraction', '云端封装的主要价值是什么？', ['降低使用复杂度并统一安全机制', '取消所有责任', '让数据不可见'], 0, '平台集中承担基础设施复杂度。'),
    },
    {
      id: 'c5-agentize-basics', source: { start: 2824.97, end: 2867.96, speakers: [3] },
      title: '先把共通基础工作 Agent（智能体）化，再处理高度专业场景',
      takeaway: '市场调研等通用任务更适合早期系统化，组织变化后再逐步扩展到复杂专业流程。',
      beginner: '先自动整理会议和收集资料，再考虑让系统独立完成高风险专业决策。',
      example: '嘉宾认为公司转型后有大量基础工作需要 Agent（智能体）化；系统搭得好，人投入少，搭得不好，人仍要不断补救。',
      principle: '任务选择应考虑重复度、标准清晰度、数据可得性和失败影响。基础工作通常更容易形成可验证闭环。',
      misconception: '基础工作不等于低价值。节省频繁重复的小时间，累计后可能产生很大组织收益。',
      extension: '建立任务组合时，可用价值与风险二维矩阵决定先后顺序，而不是只追求最炫目的场景。',
      terms: ['agent', 'workflow', 'evaluation'],
      check: check('c5-q15', 'c5-agentize-basics', '早期最适合 Agent（智能体）化什么任务？', ['重复且标准较清楚的基础工作', '最高风险决策', '没有数据的任务'], 0, '清晰反馈和较低风险有利于形成闭环。'),
    },
  ],
  quiz: [
    check('c5-quiz-1', 'c5-objective-subjective', '主观任务能否评估？', ['不能', '能，但需多维标准和人类判断'], 1, '主观不等于没有标准。'),
    check('c5-quiz-2', 'c5-wide-permissions', '权限越大是否越先进？', ['是', '不是，风险半径也扩大'], 1, '权限应与任务和审核匹配。'),
    check('c5-quiz-3', 'c5-general-agent', '专属智能体优势来自哪里？', ['具体上下文与反馈', '名字不同', '无需数据'], 0, '长期任务状态提高适配。'),
    check('c5-quiz-4', 'c5-smb', '中小企业为什么可能较早采用？', ['决策链较短', '永远不需要安全', '没有员工'], 0, '较少层级有利于试点。'),
    check('c5-quiz-5', 'c5-enterprise-obstacles', '大企业转型先选什么场景？', ['低风险且边界清楚', '跨全部部门高风险流程', '没有负责人'], 0, '可控试点能降低迁移风险。'),
    check('c5-quiz-6', 'c5-domain-expertise', '平台能否替用户定义业务目标？', ['可以全部替代', '不能，用户仍需提供任务判断'], 1, '业务价值必须由领域责任者定义。'),
    check('c5-quiz-7', 'c5-agentize-basics', '基础任务为什么值得做？', ['重复节省会累积', '因为永远无风险', '只为展示技术'], 0, '高频小收益可形成大总量。'),
  ],
}
