import type { Chapter, QuizQuestion } from '../types'

const check = (id: string, unitId: string, prompt: string, options: string[], answer: number, explanation: string): QuizQuestion => ({ id, unitId, prompt, options, answer, explanation })

export const chapter4: Chapter = {
  id: 'chapter-4', number: 4, title: '从 AI Assisted（人工智能辅助）到 AI Driven（人工智能主导）',
  source: { start: 1866.98, end: 2343.21 },
  objectives: [
    '解释为什么系统化后的审核成本不同于“人工智能做完，人从头重做”。',
    '分清模型能力、Agent Architecture（智能体架构）和组织准备度三个转型条件。',
    '学会从安全、延迟、成本和可维护性四个维度 Criticize（批评审查）规划。',
  ],
  interaction: { id: 'plan-critic', kind: 'plan', title: 'Planning Critic（规划评审器）', description: '不替人工智能重写方案，而是指出薄弱点，让方案根据架构原则逐轮提高。' },
  recap: '人工智能让执行和试验变便宜后，人的高价值工作转向提出约束、批评计划和沉淀可复用原则。',
  next: '下一章把视角移到市场与客户：个人 Agent（智能体）、权限、主观评价和 SaaS（软件即服务）重构。',
  units: [
    {
      id: 'c4-review-objection', source: { start: 1866.98, end: 1893.47, speakers: [1, 3] },
      title: '“还要人看一遍，不如自己做”只描述了没有系统化的状态',
      takeaway: '如果人工智能输出没有结构、证据和风险标记，人确实可能被迫从头检查；好的系统会把审核集中到关键点。',
      beginner: '助手把一堆无来源资料扔给你，你只能重查；如果他给出来源、比较表和不确定项，你只需核验关键证据。',
      example: '主持人用写文章类比：发现一个小错误却要通读全文。嘉宾回答，完整 AI System（人工智能系统）建立后，时间和成本结构会明显改变。',
      principle: '审核成本取决于可追踪性、模块化和验证工具。系统应让人知道改了什么、依据是什么、哪里高风险，而不是只交付最终文本。',
      misconception: '不能因为未来可能系统化，就忽视今天真实存在的复核成本。转型应测量总时间，而不是只看生成时间。',
      extension: '差异化审核把低风险结果自动验证，把高风险判断展示给人，能够减少无差别通读。',
      terms: ['review', 'reliable', 'harness-engineering'],
      check: check('c4-q1', 'c4-review-objection', '怎样真正降低复核成本？', ['只让生成更快', '提供证据、结构和风险标记', '取消责任'], 1, '审核者需要快速定位变化和关键风险。'),
    },
    {
      id: 'c4-shared-goal', source: { start: 1893.47, end: 1921.98, speakers: [3] },
      title: '组织转型需要共同目标，而不是少数人的局部自动化',
      takeaway: '只要关键环节仍拒绝新流程，交接就会在新旧方式之间反复转换，整体改造时间被拉长。',
      beginner: '一条流水线中一半用电子订单、一半坚持手写，每次交接都要重新录入，可能比统一使用任何一种方式更慢。',
      example: '嘉宾指出团队中只要有一部分人认为“还不如人工做”，组织改造就会更久、更不顺利。',
      principle: '端到端流程需要共同状态、数据和责任定义。局部效率只有跨过团队边界，才会成为组织效率。',
      misconception: '共同目标不等于压制异议。质疑可以帮助发现风险，但应进入可验证实验，而不是长期停留在立场争论。',
      extension: '可以用双轨试点比较旧流程与新流程的总周期、错误率和人员负担，再决定是否扩大。',
      terms: ['alignment', 'mindset', 'deployment'],
      check: check('c4-q2', 'c4-shared-goal', '新旧流程混用为什么可能更慢？', ['交接时不断转换和重复录入', '工具颜色不同', '员工人数太少'], 0, '接口不统一会创造额外翻译与确认工作。'),
    },
    {
      id: 'c4-capability-evolution', source: { start: 1921.98, end: 1995.56, speakers: [1, 2, 3] },
      title: '从辅助、参与到主导，是模型与系统能力共同推进的',
      takeaway: '一年以前不成立的流程，可能因基础模型、智能体架构和基础设施同时提升而变得可行。',
      beginner: '自动驾驶不是只靠更聪明的算法，还需要传感器、地图、计算平台和道路规则共同成熟。',
      example: '节目回顾 2025 年上半年仍以人为主、人工智能辅助；下半年发现效率提升有限，开始把生产力工具的使用者从人转向人工智能。',
      principle: 'AI Assisted（人工智能辅助）提供建议，AI Participating（人工智能参与）执行部分步骤，AI Driven（人工智能主导）根据状态推动流程。成熟度取决于能力和控制机制。',
      misconception: '主导不意味着所有任务都适合自动化。开放目标、伦理判断和高风险责任仍需要人保持控制。',
      extension: '评估成熟度时应问系统能否独立处理异常，而不只看正常路径能完成多少步骤。',
      terms: ['ai-first', 'agent', 'architecture'],
      check: check('c4-q3', 'c4-capability-evolution', '为什么一年后同一设想可能变得可行？', ['模型、架构和基础设施共同提升', '需求自动消失', '不再需要测试'], 0, '多个条件共同跨过可用门槛。'),
    },
    {
      id: 'c4-evolution-cost', source: { start: 1995.56, end: 2058.48, speakers: [2, 3] },
      title: '组织理解过程可能耗费一两个月，不能从转型故事里删掉',
      takeaway: '即使最终重构很快，市场与工程团队寻找新协作方式仍然需要试错和对话。',
      beginner: '搬家当天很快，但决定住哪里、分配房间和适应新路线可能花更久。',
      example: '节目提到市场和工程曾用一两个月反复探索更好协作方式；同时基础模型和 Agent Infrastructure（智能体基础设施）进步才让后续重构成立。',
      principle: '技术准备度与组织准备度是两条不同曲线。技术可行不代表角色、信任和评价标准已经同步。',
      misconception: '不要只展示“两周完成”而忽略之前数月的认知准备，否则会让其他团队低估转型成本。',
      extension: '转型时间线应包含发现问题、建立共识、试点、迁移和稳定运行，而不仅是写代码阶段。',
      terms: ['alignment', 'mindset', 'agent'],
      check: check('c4-q4', 'c4-evolution-cost', '两周重构前还有什么成本？', ['组织理解和协作试错', '完全没有', '只购买电脑'], 0, '技术实施之前已经经历了认知与流程探索。'),
    },
    {
      id: 'c4-refactor-timeline', source: { start: 2058.48, end: 2104.84, speakers: [1, 2] },
      title: '“两周重构”是特定阶段案例，不是重构工期公式',
      takeaway: '团队先在八九月意识到问题，次年一月才正式用约两周重构代码架构和开发流程。',
      beginner: '两周是正式施工时间，不包含之前发现问题、画图、沟通和准备材料的时间。',
      example: '嘉宾描述去年八九月意识到需要改变，花时间对齐 Mindset（思维方式），今年一月春节前后用约两周完成主要架构重构。',
      principle: '案例说明人工智能降低实施成本，但结果依赖小团队、已有经验、产品阶段和可接受风险。',
      misconception: '不要把工期作为能力竞赛。仓促重写成熟系统可能造成迁移失败、数据风险和长期维护问题。',
      extension: '渐进替换可以把旧系统与新系统并行运行，通过流量切分减少一次性重写风险。',
      terms: ['architecture', 'mindset', 'deployment'],
      check: check('c4-q5', 'c4-refactor-timeline', '怎样正确理解两周数字？', ['特定团队实施阶段的案例', '任何公司标准工期', '不包含任何准备也能复制'], 0, '案例条件决定数字是否可参考。'),
    },
    {
      id: 'c4-planning-score', source: { start: 2104.84, end: 2160.57, speakers: [1, 2] },
      title: 'Planning（规划）从 50 分到 90 分，是嘉宾的主观能力评价',
      takeaway: '人工智能从需要人重写方案，进步到人可以通过对话指出缺陷并让它自行修订。',
      beginner: '以前助手交来的方案只有一半能用，你要重写；现在方案大体可用，你主要负责指出遗漏和要求再修改。',
      example: 'Peter（彼得）把一年前 Planning（规划）能力评价为约 50 分、现在约 90 分，并称新架构没有手写代码或直接修改计划文本。',
      principle: '分数表达个人经验，不是统一测评。真正变化是人机协作接口从“代写与修改”变成“审查与反馈”。',
      misconception: '90 分不代表计划可以直接执行。剩余安全、延迟和架构缺陷可能恰好决定系统能否上线。',
      extension: '评估规划质量可以检查目标完整、依赖明确、风险覆盖、验证方法和回退方案，而不是只给总分。',
      terms: ['planning', 'criticize', 'review'],
      check: check('c4-q6', 'c4-planning-score', '规划分数最重要的含义是什么？', ['协作从重写转向审查反馈', '存在统一官方考试', '计划不再需要验证'], 0, '分数是个人评价，背后的协作变化更值得学习。'),
    },
    {
      id: 'c4-architect-value', source: { start: 2160.57, end: 2209.49, speakers: [1, 2] },
      title: 'Architecture（架构者）的价值是发现计划没有看到的约束',
      takeaway: '人工智能可以生成完整外观的方案，资深判断要识别安全、延迟和长期演进中的薄弱点。',
      beginner: '旅行计划看起来很详细，但熟悉当地的人会发现雨季封路、签证和换乘时间根本不成立。',
      example: '节目把 CTO（首席技术官）或 Tech Lead（技术负责人）的价值描述为找到 AI Planning（人工智能规划）中的 Security（安全）和 Latency（延迟）缺陷。',
      principle: '架构经验包含隐性约束和失败模式。Criticize（批评审查）与 Challenge（质疑挑战）迫使计划说明依据并考虑替代方案。',
      misconception: '批评不是否定人工智能，也不是只挑错。高质量批评要说明风险、证据和可行改进方向。',
      extension: '可以维护架构检查表，但检查表不能替代判断，因为新系统会出现历史上没有的组合风险。',
      terms: ['architecture', 'tech-lead', 'criticize', 'challenge'],
      check: check('c4-q7', 'c4-architect-value', '高质量架构批评应包含什么？', ['风险依据和改进方向', '只说不喜欢', '要求重写全部内容'], 0, '具体约束才能推动计划改进。'),
    },
    {
      id: 'c4-reusable-skills', source: { start: 2209.49, end: 2243.61, speakers: [1, 2] },
      title: '把一次批评沉淀为 Skill（技能规则），才形成组织记忆',
      takeaway: '安全与架构原则被写成可引用规则后，下一次计划和其他工程师都能复用。',
      beginner: '老师不只改正一道错题，还总结“遇到这种题先检查单位”，全班以后都能使用。',
      example: '嘉宾把沙箱与宿主交互原则变成 Skill（技能规则），下一次只需要求系统 Follow Principle（遵循原则），团队成员也能共同引用。',
      principle: '可复用规则把个人隐性经验转成组织可访问资产。规则应包含适用条件、原因、示例和违反时的处理。',
      misconception: '规则积累越多不一定越好。冲突、过期或缺少适用范围的规则会让计划僵化。',
      extension: '规则需要版本、负责人和复审日期，像代码一样维护，才能避免组织知识陈旧。',
      terms: ['skill-rule', 'sandbox', 'review'],
      check: check('c4-q8', 'c4-reusable-skills', '技能规则带来什么价值？', ['让经验跨任务和人员复用', '取消所有判断', '增加提示词长度'], 0, '它把一次经验转化为组织记忆。'),
    },
    {
      id: 'c4-productivity-numbers', source: { start: 2243.61, end: 2296.28, speakers: [1, 2] },
      title: '100 人四五个月与不足 10 人两周，比较前要先对齐范围',
      takeaway: '节目数字展示巨大生产率杠杆，但必须确认产品范围、质量标准和统计口径是否相同。',
      beginner: '两支队伍都说“建了一栋房”，一支包含装修和长期维护，另一支只完成样板间，人数和时间不能直接比。',
      example: '嘉宾估计传统方式开发当前产品至少约 100 人、四五个月；现在工程团队不足 10 人，第一阶段 Deployment（部署）约两周。',
      principle: '生产率比较应固定输出范围、可靠性、成本和后续维护。人工智能可能显著减少实现时间，但不会自动消除所有业务工作。',
      misconception: '不能把人数缩减直接等同于利润或产品成功。市场、支持、合规和客户采用仍可能成为主要成本。',
      extension: '更稳健的指标包括每个有效实验成本、从需求到验证的周期，以及单位收入所需总投入。',
      terms: ['deployment', 'reliable', 'topline-metrics'],
      check: check('c4-q9', 'c4-productivity-numbers', '比较团队效率前先确认什么？', ['输出范围和质量口径', '办公地点', '成员昵称'], 0, '口径不同会让倍数失去意义。'),
    },
    {
      id: 'c4-bottleneck-reversal', source: { start: 2296.28, end: 2343.21, speakers: [1, 3] },
      title: '开发从落后市场四五个月，变成领先市场三四个月',
      takeaway: '当技术瓶颈被突破，组织整体速度并不会无限提高，瓶颈会转移到市场理解与运营。',
      beginner: '餐厅厨房突然能做十倍菜，但服务员、菜单和顾客数量不变，真正限制营业额的环节就换了。',
      example: '节目描述传统 SaaS（软件即服务）销售常提前承诺未来四五个月功能；新状态下技术团队反而领先 Marketing Team（市场团队）三四个月。',
      principle: '系统吞吐量由最窄环节决定。开发加速后，需要重新设计市场验证、功能发现、支持和客户教育。',
      misconception: '市场追不上不一定说明市场团队效率低。市场价值更主观，客户采用也需要信任和时机。',
      extension: '瓶颈管理要求持续观察等待队列和未利用产能，避免继续优化已经不是限制因素的环节。',
      terms: ['saas', 'go-to-market', 'feature'],
      check: check('c4-q10', 'c4-bottleneck-reversal', '开发加速后最可能发生什么？', ['瓶颈转移到市场和运营', '所有瓶颈消失', '不再需要客户'], 0, '局部能力提高会让其他环节成为新的限制。'),
    },
  ],
  quiz: [
    check('c4-quiz-1', 'c4-review-objection', '什么能降低人工审核负担？', ['可追踪证据和风险标记', '只增加生成速度', '隐藏修改'], 0, '结构化证据让人聚焦关键点。'),
    check('c4-quiz-2', 'c4-capability-evolution', '流程成熟度应关注什么？', ['异常处理能力', '只看正常演示', '按钮数量'], 0, '真实系统必须处理失败和例外。'),
    check('c4-quiz-3', 'c4-planning-score', '90 分计划能否直接执行？', ['一定可以', '仍需审查关键缺陷'], 1, '剩余缺陷可能影响安全与上线。'),
    check('c4-quiz-4', 'c4-reusable-skills', '规则为什么需要版本和复审？', ['会冲突或过期', '为了增加文档', '因为不能复用'], 0, '组织知识也需要维护。'),
    check('c4-quiz-5', 'c4-productivity-numbers', '人数倍数能否直接外推？', ['能', '不能，要对齐范围和条件'], 1, '产品范围与质量标准可能不同。'),
    check('c4-quiz-6', 'c4-bottleneck-reversal', '局部效率提高后下一步做什么？', ['寻找新的系统瓶颈', '继续只优化同一环节', '停止测量'], 0, '整体速度由当前最窄环节决定。'),
  ],
}
