import type { Chapter, QuizQuestion } from '../types'

const check = (
  id: string,
  unitId: string,
  prompt: string,
  options: string[],
  answer: number,
  explanation: string,
): QuizQuestion => ({ id, unitId, prompt, options, answer, explanation })

export const chapter1: Chapter = {
  id: 'chapter-1',
  number: 1,
  title: '从 Prompt Engineering（提示词工程）到 Harness（驾驭系统）',
  source: { start: 0, end: 661.44 },
  objectives: [
    '分清 Prompt Engineering（提示词工程）、Context Engineering（上下文工程）与 Harness Engineering（驾驭系统工程）的范围。',
    '理解模型能力、应用工程和 AI First（人工智能优先）组织之间的关系。',
    '能用工具、安全、测试与反馈搭建一套最小 Harness（驾驭系统）。',
  ],
  interaction: {
    id: 'scope-builder',
    kind: 'scope',
    title: '概念分层搭建器',
    description: '把请求、资料、工具、安全和反馈放入正确层级，亲手搭出一套最小系统。',
  },
  units: [
    {
      id: 'c1-evolution',
      source: { start: 0, end: 33.35, speakers: [1] },
      title: '三次进化不是换名词，而是不断扩大问题范围',
      takeaway: '从写好一句要求，到准备完整资料，再到设计一套能长期工作的系统，工程对象越来越大。',
      beginner: '第一次进化关心“我怎么问”；第二次关心“模型还需要知道什么”；第三次关心“它怎样在真实环境里一直把事情做下去”。',
      example: '请人做晚饭时，提示词是今晚做番茄炒蛋；上下文是人数、忌口和现有食材；系统工程还包括采购、灶具、安全规则、试味和下次改进。',
      principle: 'Prompt Engineering（提示词工程）优化单次输入，Context Engineering（上下文工程）组织任务所需信息，Harness Engineering（驾驭系统工程）则协调模型、工具、环境、评估和反馈。',
      misconception: '不要把三者理解成互相淘汰。好的 Harness（驾驭系统）仍然需要清楚的提示词和可靠的上下文，只是它们成为更大系统中的组成部分。',
      extension: '这体现了系统思维：局部能力提高后，瓶颈往往转移到连接、反馈和环境，而不是继续停留在单个组件上。',
      terms: ['prompt-engineering', 'context-engineering', 'harness-engineering'],
      check: check('c1-q1', 'c1-evolution', '哪一个问题属于 Harness Engineering（驾驭系统工程）？', ['怎样把一句问题写清楚', '怎样让系统发现错误后自动改进', '怎样增加一段参考资料'], 1, '自动发现、修复和持续改进涉及完整系统，而不只是一次输入。'),
    },
    {
      id: 'c1-harness-metaphor',
      source: { start: 33.35, end: 61.07, speakers: [1] },
      title: 'Harness（驾驭系统）为什么原意是挽具',
      takeaway: '挽具既不是替马奔跑，也不是把马锁死，而是引导力量、限定危险方向并让合作可控。',
      beginner: '模型像一匹力量很大的马。只告诉它“往前跑”不够，还要有方向、边界、连接方式和出现问题时的处理办法。',
      example: '导航软件不会替汽车提供动力，但它通过路线、限速、路况和重新规划，让车辆更可靠地到达目的地。',
      principle: 'Harness（驾驭系统）围绕模型提供约束与支持，使它能在真实世界持续工作、自我修复并提升表现。重点是把能力转化为可重复的结果。',
      misconception: '不要把 Harness（驾驭系统）只理解成限制模型。过度限制会让系统无法完成任务；好的设计同时提供行动空间和安全边界。',
      extension: '管理学里的授权也有相似结构：明确目标、给出资源、设置边界、观察结果并复盘，而不是逐句命令执行者。',
      terms: ['harness-engineering', 'self-healing', 'self-improvement'],
      check: check('c1-q2', 'c1-harness-metaphor', '挽具比喻最想强调什么？', ['只限制模型', '引导和约束能力', '替模型完成工作'], 1, '挽具的作用是引导并约束已有力量，让力量可以安全地用于目标。'),
    },
    {
      id: 'c1-ai-first-strategy',
      source: { start: 61.07, end: 126.63, speakers: [1] },
      title: '真正的 AI First（人工智能优先）不是给旧流程加工具',
      takeaway: '如果流程、职责和决策方式完全不变，只是每个人多用一个工具，组织仍然由旧结构主导。',
      beginner: '把电动机装在旧马车上，不一定会得到一辆好汽车。新能力往往要求重新考虑车身、控制方式和道路规则。',
      example: '产品经理用人工智能写需求、工程师用人工智能写代码、设计师用人工智能做图，但三个人节奏不同、信息不同步，整体交付反而可能更乱。',
      principle: '节目引用 Peter（彼得）的观点：许多公司自称 AI First（人工智能优先），实际只是局部工具化；真正转型需要围绕人工智能能力重新设计流程和组织结构。',
      misconception: '这不代表所有企业必须立刻取消原流程。核心是检查旧流程是否仍服务于新生产方式，而不是为了追求新潮盲目重构。',
      extension: '技术史中常见“先替代局部工具、再重构系统”的过程。电力进入工厂后，生产线并不是第一天就重新布局，而是逐渐发现旧结构限制了新能力。',
      terms: ['ai-first', 'alignment'],
      check: check('c1-q3', 'c1-ai-first-strategy', '下面哪种变化更接近 AI First（人工智能优先）？', ['每人购买一个聊天工具', '围绕人工智能重新设计交付流程', '要求员工生成更多文字'], 1, '人工智能优先强调生产流程和组织结构的变化，而不是工具数量。'),
    },
    {
      id: 'c1-guest-perspectives',
      source: { start: 126.63, end: 163.12, speakers: [1, 2, 3, 4] },
      title: '为什么这场讨论同时需要研究、产品和市场视角',
      takeaway: '系统能不能落地，不只取决于模型研究，还取决于产品化、组织协作和市场使用方式。',
      beginner: '一座桥不能只让材料专家设计，还需要结构工程、施工、交通和安全等角色共同判断。人工智能系统同样跨越多个领域。',
      example: '节目介绍 Peter（彼得）具有 Meta（脸书母公司）LLaMA（大型语言模型系列）和 Apple（苹果公司）多模态研究经历，陈凯负责公司经营，Clark（克拉克）负责 Go to Market（进入市场）并具有数据科学与机器学习背景。',
      principle: '研究背景帮助判断模型边界，工程背景负责系统架构，产品与市场背景判断用户价值。三种视角共同构成节目后续关于组织重构的证据来源。',
      misconception: '人物经历能解释观点从哪里来，但不能自动证明观点正确。学习时应同时关注案例条件、适用范围和可能的利益立场。',
      extension: '跨职能讨论的价值在于暴露不同优化目标：研究关注能力，工程关注可靠性，产品关注使用，市场关注价值传递。',
      terms: ['go-to-market', 'product-sense'],
      check: check('c1-q4', 'c1-guest-perspectives', '为什么需要市场视角参与系统讨论？', ['市场能提高模型参数', '市场判断能力是否形成用户价值', '市场负责所有安全测试'], 1, '技术能力只有被用户理解和采用后才能形成产品价值。'),
    },
    {
      id: 'c1-system-components',
      source: { start: 163.12, end: 249.05, speakers: [1, 2] },
      title: 'Harness（驾驭系统）的边界比模型交互更大',
      takeaway: '完整系统要同时处理工具、安全、沙箱、宿主服务和延迟，单纯优化模型输入覆盖不了这些问题。',
      beginner: '模型像餐厅里的厨师；工具是厨具，沙箱是厨房可活动区域，宿主服务是仓库和订单系统，安全规则决定哪些设备能用，延迟决定客人要等多久。',
      example: '即使模型知道如何删除文件，系统也要决定它能看到哪些文件、是否需要确认、操作失败怎样恢复，以及执行需要多长时间。',
      principle: 'Prompt Engineering（提示词工程）和 Context Engineering（上下文工程）主要优化人与模型的交互；Harness（驾驭系统）还覆盖 Tooling（工具体系）、Security（安全）、Sandbox（沙箱）、Host Service（宿主服务）与 Latency（延迟）。',
      misconception: '不要把模型回答正确当作系统已经安全。模型知道答案与它拥有合适权限、能可靠执行、不会破坏环境是不同问题。',
      extension: '这与最小权限原则有关：系统只给任务所需的最低权限，并把敏感操作放进额外审核流程。',
      terms: ['tooling', 'sandbox', 'host-service', 'latency'],
      check: check('c1-q5', 'c1-system-components', '哪一项通常不靠提示词单独解决？', ['表达任务目标', '控制文件访问权限', '说明回答格式'], 1, '权限属于运行环境与安全架构，需要系统层机制。'),
    },
    {
      id: 'c1-success-failure',
      source: { start: 249.05, end: 292.98, speakers: [1, 2] },
      title: '同一个强模型，为什么一个工作流成功、另一个全是垃圾',
      takeaway: '结果差异往往来自系统有没有评估、反馈和停止机制，而不只是模型够不够聪明。',
      beginner: '聪明员工在目标不清、没有检查、错误继续累积的环境里，也会稳定地产生错误结果。',
      example: '节目对比两个案例：一个 Agent（智能体）一夜完成多人的 SEO（搜索引擎优化）工作；另一个内容 Pipeline（流水线）运行两天后才被发现产出不可用。',
      principle: '成功系统会持续观察质量并尽早纠偏；失败系统让错误在长链路里放大。Harness（驾驭系统）的价值在于缩短“产生错误”和“发现错误”之间的距离。',
      misconception: '不能根据一次成功案例就断言系统可靠。可靠性需要在不同输入、时间和边界情况下重复验证。',
      extension: '可以用失效成本理解这件事：越晚发现错误，返工范围越大，信任损失和资源浪费也越高。',
      terms: ['agent', 'harness-engineering', 'feedback'],
      check: check('c1-q6', 'c1-success-failure', '内容流水线最明显缺少什么？', ['更长运行时间', '及时质量反馈', '更多生成数量'], 1, '系统运行两天才发现垃圾，说明反馈和停止机制太迟。'),
    },
    {
      id: 'c1-feedback-loop',
      source: { start: 292.98, end: 334.8, speakers: [2] },
      title: '一次完成不是常态，持续改进才是系统能力',
      takeaway: 'Agent（智能体）通常不会 One-shot（一次完成）达到最佳状态，需要用户反馈或系统自我提升。',
      beginner: '第一次练习钢琴不会直接达到演奏会水平。需要听结果、找到问题、调整动作，再进行下一轮。',
      example: '用户创建广告 Agent（智能体）后，第一周的文案点击率不理想。系统可以读取反馈，调整受众、表达和预算，而不是每周从零开始。',
      principle: 'Feedback（反馈）告诉系统结果好坏；Self-healing（自我修复）恢复故障；Self-improvement（自我提升）改变策略，使后续表现更好。三者解决的问题不同。',
      misconception: '自我提升不等于系统可以无人监管。错误指标会把系统带向错误方向，因此人仍要定义什么叫“更好”。',
      extension: '反馈回路至少需要目标、观测、比较和调整四部分。缺少任何一部分，系统都无法知道是否真正进步。',
      terms: ['feedback', 'self-healing', 'self-improvement'],
      check: check('c1-q7', 'c1-feedback-loop', '系统根据点击率调整下周策略属于什么？', ['自我修复', '自我提升', '一次完成'], 1, '它不是恢复故障，而是根据结果优化后续策略。'),
    },
    {
      id: 'c1-inference-scaling',
      source: { start: 334.8, end: 394.94, speakers: [1, 2] },
      title: '给 Agent（智能体）更多时间和工具，也会放大风险',
      takeaway: '推理阶段投入越多，系统可能完成更复杂任务，但错误链、成本和上下文问题也会增加。',
      beginner: '给一个人更多时间、资料和工具，通常能做更难的项目；但资料太多会看乱，工具太多会用错，工作越久也越可能偏离目标。',
      example: '一个研究 Agent（智能体）连续搜索、整理、计算和写作数小时，比单次回答更强，但任何早期错误都可能污染后面的结论。',
      principle: 'Inference Scaling（推理阶段扩展）增加 Context（上下文）、Tooling（工具体系）和思考时间。Harness（驾驭系统）需要控制 Hallucination（幻觉）、上下文溢出和能力下降。',
      misconception: '更多上下文并不总是更好。无关、冲突或过期资料会占用注意力，使关键证据更难被识别。',
      extension: '长任务需要阶段性检查点：每完成一个子目标就验证事实、成本和方向，避免错误直到最后才暴露。',
      terms: ['inference-scaling', 'tooling', 'hallucination'],
      check: check('c1-q8', 'c1-inference-scaling', '为什么长任务更需要 Harness（驾驭系统）？', ['因为模型必须说更多字', '因为错误会沿多步骤累积', '因为工具越少越危险'], 1, '步骤越多，早期错误影响后续结果的范围越大。'),
    },
    {
      id: 'c1-engineering-gap',
      source: { start: 394.94, end: 438.74, speakers: [1, 3] },
      title: '模型会做，不等于产品已经能稳定提供',
      takeaway: '演示一个能力可能很快，把它变成安全、稳定、可维护的产品却需要大量看不见的工程。',
      beginner: '会做一道菜和经营一家每天稳定出餐的餐厅不是同一件事。后者还要处理采购、卫生、排班、成本和投诉。',
      example: '业务人员看到一个简单功能，可能觉得几天就能做完；开发团队却要考虑权限、数据、异常、兼容、测试和上线，传统情况下可能花两三个月。',
      principle: '大型语言模型能力只是系统中的核心组件。工程层要解决运行环境、接口、失败恢复、监控和规模化，这些共同决定用户能否真正使用能力。',
      misconception: '不要把工程时间简单解释为团队效率低。也不要反过来用“工程复杂”掩盖不必要的流程，应该拆出真正的风险与约束。',
      extension: '可用性、可靠性和可维护性是三个不同目标：今天能运行，不代表明天稳定，也不代表半年后容易修改。',
      terms: ['architecture', 'integration-test', 'review'],
      check: check('c1-q9', 'c1-engineering-gap', '从演示到产品通常新增了什么工作？', ['只增加界面颜色', '安全、异常和维护机制', '删除所有测试'], 1, '产品化需要处理真实环境中的风险和长期维护。'),
    },
    {
      id: 'c1-dynamic-signals',
      source: { start: 438.74, end: 490.38, speakers: [1, 2] },
      title: '静态 Harness（驾驭系统）与动态 Harness（驾驭系统）',
      takeaway: '节目认为真正重要的非共识，是系统不只搭好一次，而要持续吸收新信号并改变。',
      beginner: '静态系统像印好的纸质地图；动态系统像实时导航，会根据堵车、封路和目的地变化重新规划。',
      example: '市场发现新需求、产品得到使用数据、基础设施出现延迟，这些 Signal（信号）都可以送入系统，影响下一轮优先级。',
      principle: '动态 Harness（驾驭系统）持续接收 Marketing Signal（市场信号）、Product Signal（产品信号）、User Signal（用户信号）和 Infrastructure Signal（基础设施信号），由人工智能主导部分迭代。',
      misconception: '动态不等于每个信号都立刻改变产品。噪声、短期波动和恶意输入需要过滤，否则系统会频繁摇摆。',
      extension: '信号质量取决于相关性、时效性和可信度。优秀反馈系统不仅收集数据，还要判断数据能否代表真实目标。',
      terms: ['signal', 'feedback', 'self-improvement'],
      check: check('c1-q10', 'c1-dynamic-signals', '动态 Harness（驾驭系统）新增了什么能力？', ['固定一套提示词', '根据新信号持续调整', '停止收集用户数据'], 1, '动态系统会把新信号送回决策过程。'),
    },
    {
      id: 'c1-speed-story',
      source: { start: 490.38, end: 540.61, speakers: [1] },
      title: '一天多轮迭代的案例，重点不是代码数量',
      takeaway: '上午做功能、当天测试和重写的价值，在于缩短“想法到真实反馈”的周期。',
      beginner: '与其花六周猜用户喜欢什么，不如先做一个小版本，当天观察，再根据结果修改。',
      example: '节目描述一家 25 人公司约 99% 代码由人工智能生成：10 点完成一个功能，中午做 A/B Test（对照测试），15 点砍掉部分，17 点重写更好版本。',
      principle: '速度优势来自实现、测试、数据和决策连成闭环。单纯生成更多代码可能只会制造更多维护负担。',
      misconception: '节目中的 99% 是特定公司的自述案例，不应直接外推为所有团队的标准，也不能代替质量、成本和业务结果。',
      extension: '更有意义的指标是从想法到证据的时间、有效实验数量和最终业务改善，而不是每天生成多少行代码。',
      terms: ['ai-first', 'feedback', 'rollout'],
      check: check('c1-q11', 'c1-speed-story', '一天多轮迭代真正缩短了什么？', ['从想法到真实反馈的时间', '每段代码的字符数', '员工休息时间'], 0, '关键是更快获得证据并据此修改产品。'),
    },
    {
      id: 'c1-two-harness-layers',
      source: { start: 540.61, end: 592.96, speakers: [1, 2] },
      title: '平台自身与用户 Agent（智能体）需要两层 Harness（驾驭系统）',
      takeaway: '平台要先保证自己的智能体系统可靠，还要帮助用户搭建属于自己的任务系统。',
      beginner: '云厨房既要管理自己的食品安全和配送系统，也要给每个入驻商家提供制作、检查和出餐工具。',
      example: '节目区分 Crew（产品名）自身 Agent（智能体）系统的 Harness（驾驭系统），以及用户使用平台创建 Agent（智能体）时所需的 Harness（驾驭系统）。',
      principle: '第一层关心平台基础能力的安全、性能和稳定；第二层关心用户任务的目标、数据、工具和反馈。两层失败都会影响最终结果。',
      misconception: '不要以为平台可靠就代表用户创建的每个 Agent（智能体）都可靠。用户目标不清、数据错误或评估不当仍会造成失败。',
      extension: '多租户软件也有类似结构：平台提供统一基础设施，每个客户在自己的数据、权限和流程中配置具体应用。',
      terms: ['agent', 'harness-engineering', 'sandbox'],
      check: check('c1-q12', 'c1-two-harness-layers', '为什么需要两层 Harness（驾驭系统）？', ['平台可靠与用户任务可靠是不同问题', '为了把按钮做成两种颜色', '因为用户不能定义任务'], 0, '基础设施和具体业务任务各有自己的风险与反馈。'),
    },
    {
      id: 'c1-tools-vs-transformation',
      source: { start: 592.96, end: 661.44, speakers: [1, 2, 4] },
      title: '每个人都用人工智能，整体效率仍可能没有提升',
      takeaway: '局部速度提升后，如果信息和节奏不同步，Alignment（对齐）成本会吞掉效率收益。',
      beginner: '八个人分别开快车，但没有统一路线和交通规则，车速越快，互相等待和碰撞的风险反而越高。',
      example: '节目中的远程团队曾让工程师、产品经理和设计师各自使用人工智能，但个人进度不同，团队同步信息的成本变得更高。',
      principle: 'AI Native（人工智能原生）或 AI First（人工智能优先）要求围绕人工智能能力重建工作流，而不是把工具叠加到旧交接链。设计、规划和测试也要进入同一 Harness（驾驭系统）。',
      misconception: '组织重构不是简单裁掉协调角色。只有共享信息、决策标准和责任机制建立后，减少人工交接才可能真正降低成本。',
      extension: '局部优化可能伤害全局，这在系统工程中很常见。评价转型应看端到端交付，而不是只看单个人完成任务的速度。',
      terms: ['ai-first', 'alignment', 'harness-engineering'],
      check: check('c1-q13', 'c1-tools-vs-transformation', '个人效率提高但整体效率不升，最可能缺少什么？', ['更多工具账号', '共享流程和对齐机制', '更长的会议'], 1, '局部加速必须通过共享系统转化为端到端效率。'),
    },
  ],
  quiz: [
    check('c1-quiz-1', 'c1-evolution', '从范围看，哪一项最大？', ['提示词', '上下文', '完整 Harness（驾驭系统）'], 2, '完整系统包含输入、资料、工具、安全、测试与反馈。'),
    check('c1-quiz-2', 'c1-system-components', '沙箱主要解决什么问题？', ['隔离运行风险', '让文字更优美', '提高市场销量'], 0, 'Sandbox（沙箱）限制程序可访问的环境和资源。'),
    check('c1-quiz-3', 'c1-feedback-loop', '恢复故障属于哪种能力？', ['Self-healing（自我修复）', 'Self-improvement（自我提升）', 'A/B Test（对照测试）'], 0, '自我修复关注从故障恢复，自我提升关注策略变好。'),
    check('c1-quiz-4', 'c1-inference-scaling', '更多上下文一定更好吗？', ['一定', '不一定，噪声会稀释关键信息'], 1, '上下文质量和相关性比单纯数量更重要。'),
    check('c1-quiz-5', 'c1-dynamic-signals', '动态系统为什么要过滤信号？', ['避免被噪声带着频繁摇摆', '避免系统学习', '减少所有数据'], 0, '并非每个短期变化都代表真实目标改变。'),
    check('c1-quiz-6', 'c1-tools-vs-transformation', '使用人工智能工具等于 AI First（人工智能优先）吗？', ['等于', '不等于，还要重构流程和组织'], 1, '工具使用是局部变化，人工智能优先是系统性变化。'),
  ],
}
