import type { GlossaryEntry } from './types'

export const glossary: GlossaryEntry[] = [
  { key: 'prompt-engineering', english: 'Prompt Engineering', chinese: '提示词工程', beginner: '把一次要求表达清楚，让模型更容易给出合适答案。' },
  { key: 'context-engineering', english: 'Context Engineering', chinese: '上下文工程', beginner: '为模型准备完成任务所需的资料、规则和历史。' },
  { key: 'harness-engineering', english: 'Harness Engineering', chinese: '驾驭系统工程', beginner: '围绕模型搭建工具、安全、测试、反馈和改进机制。' },
  { key: 'agent', english: 'Agent', chinese: '智能体', beginner: '能够观察环境、调用工具并连续完成任务的人工智能系统。' },
  { key: 'ai-first', english: 'AI First', chinese: '人工智能优先', beginner: '从流程和组织层面让人工智能成为主要生产力，而不只是辅助工具。' },
  { key: 'tooling', english: 'Tooling', chinese: '工具体系', beginner: '让系统能够搜索、计算、读写数据或执行操作的一组工具。' },
  { key: 'sandbox', english: 'Sandbox', chinese: '沙箱', beginner: '把程序限制在安全范围内运行的隔离环境。' },
  { key: 'host-service', english: 'Host Service', chinese: '宿主服务', beginner: '在沙箱外提供数据、权限和业务能力的主系统。' },
  { key: 'latency', english: 'Latency', chinese: '延迟', beginner: '从发出请求到得到结果需要等待的时间。' },
  { key: 'hallucination', english: 'Hallucination', chinese: '幻觉', beginner: '模型生成看似合理但实际上错误或没有依据的内容。' },
  { key: 'feedback', english: 'Feedback', chinese: '反馈', beginner: '把结果好坏重新送回系统，帮助下一轮调整。' },
  { key: 'self-healing', english: 'Self-healing', chinese: '自我修复', beginner: '系统发现故障后自动定位并恢复工作的能力。' },
  { key: 'self-improvement', english: 'Self-improvement', chinese: '自我提升', beginner: '系统根据历史结果持续改进策略和表现。' },
  { key: 'inference-scaling', english: 'Inference Scaling', chinese: '推理阶段扩展', beginner: '在执行任务时投入更多时间、上下文和工具调用。' },
  { key: 'signal', english: 'Signal', chinese: '信号', beginner: '能帮助系统判断结果和下一步行动的数据。' },
  { key: 'rollout', english: 'Roll out', chinese: '放量发布', beginner: '把验证有效的改动逐步开放给更多用户。' },
  { key: 'fallback', english: 'Fall back', chinese: '回退', beginner: '新方案有问题时恢复到较稳定的旧方案。' },
  { key: 'ci-cd', english: 'CI/CD', chinese: '持续集成与持续部署', beginner: '自动检查、合并、测试和发布代码的流程。' },
  { key: 'integration-test', english: 'Integration Test', chinese: '集成测试', beginner: '检查多个模块连接起来后能否正确合作。' },
  { key: 'unit-test', english: 'Unit Test', chinese: '单元测试', beginner: '检查一个小功能或函数是否按预期工作。' },
  { key: 'bug-triage', english: 'Bug Triage', chinese: '错误分诊', beginner: '判断问题的类型、风险、优先级和处理人。' },
  { key: 'autofixing', english: 'Autofixing', chinese: '自动修复', beginner: '由系统直接提出并提交低风险问题的修复方案。' },
  { key: 'architecture', english: 'Architecture', chinese: '系统架构', beginner: '决定系统各部分如何分工、连接并满足安全和性能要求。' },
  { key: 'review', english: 'Review', chinese: '审核', beginner: '检查结果是否符合目标、规则和风险要求。' },
  { key: 'go-to-market', english: 'Go to Market', chinese: '进入市场', beginner: '把产品价值传递给目标客户并形成销售的完整过程。' },
  { key: 'general-agent', english: 'General Agent', chinese: '通用智能体', beginner: '面向很多用户和任务提供通用能力的智能体。' },
  { key: 'smb', english: 'SMB', chinese: '中小企业', beginner: '规模相对较小、决策链较短的企业客户。' },
  { key: 'mcp', english: 'MCP', chinese: '模型上下文协议', beginner: '让人工智能系统以统一方式连接数据和工具的协议。' },
  { key: 'api', english: 'API', chinese: '应用程序接口', beginner: '让不同软件按照约定交换数据和调用能力的入口。' },
  { key: 'alignment', english: 'Alignment', chinese: '对齐', beginner: '让团队或系统对目标、信息和判断标准形成一致理解。' },
  { key: 'implementation', english: 'Implementation', chinese: '实现', beginner: '把想法真正做成可以运行和使用的产品。' },
  { key: 'product-sense', english: 'Product Sense', chinese: '产品感', beginner: '判断用户需要什么以及什么方案更有价值的能力。' },
  { key: 'pre-training', english: 'Pre-training', chinese: '预训练', beginner: '先用大量数据训练通用能力，再适配具体任务。' },
  { key: 'mindset', english: 'Mindset', chinese: '思维方式', beginner: '面对工作、风险和角色变化时采用的一组基本看法。' },
  { key: 'deployment', english: 'Deployment', chinese: '部署', beginner: '把完成的软件版本发布到真实运行环境。' },
  { key: 'feature', english: 'Feature', chinese: '产品功能', beginner: '用户可以感知和使用的一项产品能力。' },
  { key: 'topline-metrics', english: 'Topline Metrics', chinese: '核心业务指标', beginner: '直接反映增长、使用或收入等主要结果的数据。' },
  { key: 'ab-test', english: 'A/B Test', chinese: '对照测试', beginner: '把不同版本给相似人群使用，用数据比较实际效果。' },
  { key: 'end-to-end-test', english: 'End-to-end Test', chinese: '端到端测试', beginner: '像真实用户一样从开始到结束检查完整流程。' },
  { key: 'log', english: 'Log', chinese: '运行日志', beginner: '系统在运行过程中留下的事件和错误记录。' },
  { key: 'incident', english: 'Incident', chinese: '线上事故', beginner: '影响真实用户或业务连续性的系统故障。' },
  { key: 'remote', english: 'Remote', chinese: '远程办公', beginner: '团队成员不在同一地点，通过网络协作。' },
  { key: 'prd', english: 'PRD', chinese: '产品需求文档', beginner: '说明产品为什么做、为谁做以及要实现什么的文档。' },
  { key: 'coding', english: 'Coding', chinese: '编写代码', beginner: '把方案转换成计算机可以执行的程序。' },
  { key: 'regression-test', english: 'Regression Test', chinese: '回归测试', beginner: '确认新改动没有破坏原来已经正常的功能。' },
  { key: 'corner-case', english: 'Corner Case', chinese: '边界情况', beginner: '只在少见输入或特殊条件组合下出现的问题。' },
  { key: 'race-condition', english: 'Race Condition', chinese: '竞态条件', beginner: '多个操作同时发生时，先后顺序不同导致的不稳定错误。' },
  { key: 'production', english: 'Production', chinese: '生产环境', beginner: '真实用户正在使用的正式系统环境。' },
  { key: 'parallel', english: 'Parallel', chinese: '并行', beginner: '多个任务同时推进，而不是一个完成后再做下一个。' },
  { key: 'pull-request', english: 'Pull Request', chinese: '代码合并请求', beginner: '把一组代码改动提交给团队检查并准备合并。' },
  { key: 'authentication', english: 'Authentication', chinese: '身份认证', beginner: '确认调用者是谁以及是否有权访问某项能力。' },
  { key: 'operator', english: 'Operator', chinese: '系统操作者', beginner: '按既定结构维护、运行和处理日常任务的人。' },
  { key: 'reliable', english: 'Reliable', chinese: '可靠', beginner: '在不同时间和条件下都能稳定完成目标。' },
  { key: 'agent-economy', english: 'Agent Economy', chinese: '智能体经济', beginner: '智能体参与搜索、比较、购买和交易决策的经济活动。' },
  { key: 'saas', english: 'SaaS', chinese: '软件即服务', beginner: '通过网络持续提供、按服务方式使用的软件产品。' },
  { key: 'dashboard', english: 'Dashboard', chinese: '仪表盘', beginner: '集中展示任务、状态和指标的可视化界面。' },
  { key: 'planning', english: 'Planning', chinese: '规划', beginner: '在执行前确定目标、步骤、约束、风险和验证方法。' },
  { key: 'criticize', english: 'Criticize', chinese: '批评审查', beginner: '指出方案中缺失、错误或不合理的部分。' },
  { key: 'challenge', english: 'Challenge', chinese: '质疑挑战', beginner: '要求方案解释依据、考虑替代路线并修正薄弱点。' },
  { key: 'skill-rule', english: 'Skill', chinese: '技能规则', beginner: '把可复用经验写成系统下次能够遵循的明确原则。' },
  { key: 'open-source', english: 'Open Source', chinese: '开源', beginner: '公开代码并允许他人按许可证查看、使用和改进。' },
  { key: 'framework', english: 'Framework', chinese: '开发框架', beginner: '提供常用结构和能力，帮助系统更快搭建的基础工具。' },
  { key: 'tech-lead', english: 'Tech Lead', chinese: '技术负责人', beginner: '负责关键技术方向、方案质量和团队技术决策的人。' },
  { key: 'evaluation', english: 'Evaluation', chinese: '评估', beginner: '用明确标准判断结果是否达到目标。' },
  { key: 'workflow', english: 'Workflow', chinese: '工作流', beginner: '任务从开始到完成所经过的步骤、角色和状态。' },
  { key: 'permission', english: 'Permission', chinese: '权限', beginner: '规定身份可以读取哪些数据、调用哪些能力和执行哪些动作。' },
  { key: 'access', english: 'Access', chinese: '访问', beginner: '读取数据、进入系统或调用能力的行为与资格。' },
  { key: 'campaign', english: 'Campaign', chinese: '营销活动', beginner: '围绕一个市场目标组织的一系列广告、内容和投放动作。' },
  { key: 'performance', english: 'Performance', chinese: '表现', beginner: '系统在质量、速度、成本或业务结果上的实际效果。' },
  { key: 'cloud-service', english: 'Cloud Service', chinese: '云端服务', beginner: '通过网络提供计算、存储、工具和管理能力的服务。' },
  { key: 'legacy-system', english: 'Legacy System', chinese: '历史遗留系统', beginner: '长期运行但结构、技术或数据难以适应新需求的旧系统。' },
  { key: 'adoption', english: 'Adoption', chinese: '采用', beginner: '用户或组织真正开始并持续使用一种产品或工作方式。' },
]
